// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ScopeTier.
const (
	ScopeTierLocal    ScopeTier = "local"
	ScopeTierRegional ScopeTier = "regional"
)

// Valid indicates whether the value is a known member of the ScopeTier enum.
func (e ScopeTier) Valid() bool {
	switch e {
	case ScopeTierLocal:
		return true
	case ScopeTierRegional:
		return true
	default:
		return false
	}
}

// Defines values for SubmissionStatus.
const (
	SubmissionStatusApproved SubmissionStatus = "approved"
	SubmissionStatusPending  SubmissionStatus = "pending"
	SubmissionStatusRejected SubmissionStatus = "rejected"
)

// Valid indicates whether the value is a known member of the SubmissionStatus enum.
func (e SubmissionStatus) Valid() bool {
	switch e {
	case SubmissionStatusApproved:
		return true
	case SubmissionStatusPending:
		return true
	case SubmissionStatusRejected:
		return true
	default:
		return false
	}
}

// Country ISO-style country code. v1 ships with `US` and `CA`; additional
// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
// changes as data is loaded.
type Country = string

// LookupOrg defines model for LookupOrg.
type LookupOrg struct {
	// ContactUrl Optional. URL of the org's contact page.
	ContactUrl *string `json:"contact_url,omitempty"`
	Id         int64   `json:"id"`

	// MatchedRegionSlugs Slugs of the regions whose membership caused this org
	// to surface for the current lookup. A non-empty subset
	// of the org's `regions[*].slug`. Useful for
	// explainability and debugging.
	MatchedRegionSlugs []string `json:"matched_region_slugs"`
	Name               string   `json:"name"`
	Regions            []Region `json:"regions"`
	ShortDesc          string   `json:"short_desc"`
	Slug               string   `json:"slug"`

	// Tags Open-ended labels. The canonical set is documented in
	// `CLAUDE.md` (transit, safe-streets, cycling, walking,
	// vision-zero, policy, grassroots, political, neighborhood);
	// new labels may be introduced via seed data.
	Tags       []string `json:"tags"`
	WebsiteUrl string   `json:"website_url"`
}

// LookupQuery defines model for LookupQuery.
type LookupQuery struct {
	// Country ISO-style country code. v1 ships with `US` and `CA`; additional
	// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
	// changes as data is loaded.
	Country    Country `json:"country"`
	PostalCode string  `json:"postal_code"`
}

// LookupResult Response shape of `GET /api/v1/lookup`. `local` and `regional`
// are always present (possibly empty arrays).
// `resolved_ancestry` is the postal code's leaf region followed
// by all ancestors, ordered most-specific first — clients can use
// it to render breadcrumbs without walking the graph themselves.
type LookupResult struct {
	Local              []LookupOrg `json:"local"`
	Query              LookupQuery `json:"query"`
	Regional           []LookupOrg `json:"regional"`
	ResolvedAncestry   []Region    `json:"resolved_ancestry"`
	ResolvedPlaceLabel string      `json:"resolved_place_label"`
}

// MetroDetail A metro region with the approved organizations that serve it.
type MetroDetail struct {
	Orgs []Org `json:"orgs"`

	// Region A geographic unit an organization can serve. Regions form a
	// directed acyclic graph; `parent_slugs` lists the direct parents
	// (not transitive). Empty for top-of-hierarchy regions (states,
	// multi-state regions, transit federations).
	Region Region `json:"region"`
}

// MetroSummary A metro region plus its approved-org count, for the browse-by-metro panel.
type MetroSummary struct {
	OrgCount int32 `json:"org_count"`

	// Region A geographic unit an organization can serve. Regions form a
	// directed acyclic graph; `parent_slugs` lists the direct parents
	// (not transitive). Empty for top-of-hierarchy regions (states,
	// multi-state regions, transit federations).
	Region Region `json:"region"`
}

// NewSubmissionRequest Request body for `POST /api/v1/submissions`.
type NewSubmissionRequest struct {
	// Payload The proposed organization, as submitted by a member of the public.
	Payload SubmissionPayload `json:"payload"`

	// SubmitterEmail Optional. The submitter's contact email.
	SubmitterEmail *openapi_types.Email `json:"submitter_email,omitempty"`

	// SubmitterName Optional. The submitter's name.
	SubmitterName *string `json:"submitter_name,omitempty"`

	// SubmitterNote Optional. Free-form note to the moderators.
	SubmitterNote *string `json:"submitter_note,omitempty"`
}

// Org A single advocacy organization. `regions` is denormalized onto
// the organization for ergonomic JSON output — it lists every
// region the org serves, not just the regions that matched the
// current query.
type Org struct {
	// ContactUrl Optional. URL of the org's contact page.
	ContactUrl *string  `json:"contact_url,omitempty"`
	Id         int64    `json:"id"`
	Name       string   `json:"name"`
	Regions    []Region `json:"regions"`
	ShortDesc  string   `json:"short_desc"`
	Slug       string   `json:"slug"`

	// Tags Open-ended labels. The canonical set is documented in
	// `CLAUDE.md` (transit, safe-streets, cycling, walking,
	// vision-zero, policy, grassroots, political, neighborhood);
	// new labels may be introduced via seed data.
	Tags       []string `json:"tags"`
	WebsiteUrl string   `json:"website_url"`
}

// ProblemDetails Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type ProblemDetails struct {
	// Detail Human-readable explanation specific to this occurrence.
	// Safe to display to end users.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference that identifies the specific occurrence of
	// the problem — typically the request path.
	Instance *string `json:"instance,omitempty"`

	// RequestId Extension field. The server-side request ID; matches the
	// `X-Request-ID` response header. Useful for users to quote
	// when reporting bugs.
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP status code generated by the origin server. Mirrors
	// the response's status line; included in the body so it
	// survives proxies that mangle status codes.
	Status int32 `json:"status"`

	// Title Short, human-readable summary of the problem type. Should
	// not change between occurrences of the same problem type,
	// except for localization.
	Title string `json:"title"`

	// Type URI reference that identifies the problem type. When
	// absent or `about:blank`, the `title` alone identifies the
	// problem.
	Type string `json:"type"`
}

// Region A geographic unit an organization can serve. Regions form a
// directed acyclic graph; `parent_slugs` lists the direct parents
// (not transitive). Empty for top-of-hierarchy regions (states,
// multi-state regions, transit federations).
type Region struct {
	// Country ISO-style country code. v1 ships with `US` and `CA`; additional
	// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
	// changes as data is loaded.
	Country Country `json:"country"`
	Id      int64   `json:"id"`

	// Kind Free-form taxonomy for region granularity. The recommended
	// vocabulary uses country-prefixed values: `us:city`, `us:borough`,
	// `us:county`, `us:metro`, `us:state`, `us:multi-state`,
	// `us:transit-federation`, `ca:province`, `ca:regional-district`,
	// `ca:city`, `de:land`, `de:bezirk`, `de:kreisfreie-stadt`,
	// `de:transit-federation`, `fr:commune`, `fr:departement`,
	// `fr:region`, `fr:metropole`. Clients should treat unknown kinds
	// gracefully (e.g. fall back to displaying `name`).
	Kind RegionKind `json:"kind"`
	Name string     `json:"name"`

	// ParentSlugs Direct parents in the region graph. Clients can walk these
	// to render breadcrumbs without a second request.
	ParentSlugs []string `json:"parent_slugs"`

	// ScopeTier Drives result grouping in `/lookup`. `local` for city/county
	// regions; `regional` for metro/state/province/multi-state.
	ScopeTier ScopeTier `json:"scope_tier"`

	// Slug Globally unique across countries.
	Slug string `json:"slug"`
}

// RegionKind Free-form taxonomy for region granularity. The recommended
// vocabulary uses country-prefixed values: `us:city`, `us:borough`,
// `us:county`, `us:metro`, `us:state`, `us:multi-state`,
// `us:transit-federation`, `ca:province`, `ca:regional-district`,
// `ca:city`, `de:land`, `de:bezirk`, `de:kreisfreie-stadt`,
// `de:transit-federation`, `fr:commune`, `fr:departement`,
// `fr:region`, `fr:metropole`. Clients should treat unknown kinds
// gracefully (e.g. fall back to displaying `name`).
type RegionKind = string

// RejectSubmissionRequest Request body for `POST /api/v1/admin/submissions/{id}/reject`.
type RejectSubmissionRequest struct {
	// Reason Free-form note shown to the submitter if email notifications are enabled, and persisted for audit.
	Reason string `json:"reason"`
}

// ScopeTier Drives result grouping in `/lookup`. `local` for city/county
// regions; `regional` for metro/state/province/multi-state.
type ScopeTier string

// Submission A queued or processed public submission.
type Submission struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`

	// Payload The proposed organization, as submitted by a member of the public.
	Payload SubmissionPayload `json:"payload"`

	// ProcessedAt Set when status moves from `pending` to a terminal state.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	// PromotedOrgId Set on approval to the ID of the created organization.
	PromotedOrgId *int64 `json:"promoted_org_id,omitempty"`

	// RejectionReason Set on rejection.
	RejectionReason *string `json:"rejection_reason,omitempty"`

	// Status Lifecycle state of a public submission.
	Status         SubmissionStatus     `json:"status"`
	SubmitterEmail *openapi_types.Email `json:"submitter_email,omitempty"`
	SubmitterName  *string              `json:"submitter_name,omitempty"`
	SubmitterNote  *string              `json:"submitter_note,omitempty"`
}

// SubmissionPayload The proposed organization, as submitted by a member of the public.
type SubmissionPayload struct {
	// ContactUrl Optional.
	ContactUrl *string `json:"contact_url,omitempty"`
	Name       string  `json:"name"`

	// RegionSlugs Slugs of the regions this organization serves (e.g.
	// `["brooklyn-ny","nyc-metro"]`). The server resolves these
	// against the `regions` table at approval time.
	RegionSlugs []string `json:"region_slugs"`
	ShortDesc   string   `json:"short_desc"`
	Tags        []string `json:"tags"`
	WebsiteUrl  string   `json:"website_url"`
}

// SubmissionStatus Lifecycle state of a public submission.
type SubmissionStatus string

// CountryQuery ISO-style country code. v1 ships with `US` and `CA`; additional
// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
// changes as data is loaded.
type CountryQuery = Country

// MetroSlug defines model for MetroSlug.
type MetroSlug = string

// PostalCodeQuery defines model for PostalCodeQuery.
type PostalCodeQuery = string

// SubmissionID defines model for SubmissionID.
type SubmissionID = int64

// BadRequest Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type BadRequest = ProblemDetails

// InternalError Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type InternalError = ProblemDetails

// NotFound Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type NotFound = ProblemDetails

// TooManyRequests Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type TooManyRequests = ProblemDetails

// Unauthorized Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type Unauthorized = ProblemDetails

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListSubmissionsParams defines parameters for ListSubmissions.
type ListSubmissionsParams struct {
	// Status Filter by submission status. Defaults to `pending`.
	Status *SubmissionStatus `form:"status,omitempty" json:"status,omitempty"`
}

// LookupParams defines parameters for Lookup.
type LookupParams struct {
	// PostalCode US ZIP code (e.g. `11217`) or Canadian postal code or FSA
	// (e.g. `M5V` or `M5V 3A8`). Whitespace is trimmed; CA codes are
	// truncated to their 3-character FSA server-side.
	PostalCode PostalCodeQuery `form:"postal_code" json:"postal_code"`

	// Country ISO-style country code. Case-insensitive.
	Country CountryQuery `form:"country" json:"country"`
}

// RejectSubmissionJSONRequestBody defines body for RejectSubmission for application/json ContentType.
type RejectSubmissionJSONRequestBody = RejectSubmissionRequest

// CreateSubmissionJSONRequestBody defines body for CreateSubmission for application/json ContentType.
type CreateSubmissionJSONRequestBody = NewSubmissionRequest
