// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ScopeTier.
const (
	ScopeTierLocal    ScopeTier = "local"
	ScopeTierNational ScopeTier = "national"
	ScopeTierRegional ScopeTier = "regional"
)

// Valid indicates whether the value is a known member of the ScopeTier enum.
func (e ScopeTier) Valid() bool {
	switch e {
	case ScopeTierLocal:
		return true
	case ScopeTierNational:
		return true
	case ScopeTierRegional:
		return true
	default:
		return false
	}
}

// Defines values for SubmissionStatus.
const (
	SubmissionStatusApproved SubmissionStatus = "approved"
	SubmissionStatusPending  SubmissionStatus = "pending"
	SubmissionStatusRejected SubmissionStatus = "rejected"
)

// Valid indicates whether the value is a known member of the SubmissionStatus enum.
func (e SubmissionStatus) Valid() bool {
	switch e {
	case SubmissionStatusApproved:
		return true
	case SubmissionStatusPending:
		return true
	case SubmissionStatusRejected:
		return true
	default:
		return false
	}
}

// Country ISO-style country code. v1 ships with `US` and `CA`; additional
// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
// changes as data is loaded.
type Country = string

// LookupOrg defines model for LookupOrg.
type LookupOrg struct {
	// ContactUrl Optional. URL of the org's contact page.
	ContactUrl *string `json:"contact_url,omitempty"`
	Id         int64   `json:"id"`

	// MatchedRegionSlugs Slugs of the regions whose membership caused this org
	// to surface for the current lookup. A non-empty subset
	// of the org's `regions[*].slug`. Useful for
	// explainability and debugging.
	MatchedRegionSlugs []string `json:"matched_region_slugs"`
	Name               string   `json:"name"`
	Regions            []Region `json:"regions"`
	ShortDesc          string   `json:"short_desc"`
	Slug               string   `json:"slug"`

	// Tags Open-ended labels. The canonical set is documented in
	// `CLAUDE.md` (transit, safe-streets, cycling, walking,
	// vision-zero, policy, grassroots, political, neighborhood);
	// new labels may be introduced via seed data.
	Tags       []string `json:"tags"`
	WebsiteUrl string   `json:"website_url"`
}

// LookupQuery defines model for LookupQuery.
type LookupQuery struct {
	// Country ISO-style country code. v1 ships with `US` and `CA`; additional
	// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
	// changes as data is loaded.
	Country    Country `json:"country"`
	PostalCode string  `json:"postal_code"`
}

// LookupResult Response shape of `GET /api/v1/lookup`. `local` and `regional`
// are always present (possibly empty arrays).
// `resolved_ancestry` is the postal code's leaf region followed
// by all ancestors, ordered most-specific first — clients can use
// it to render breadcrumbs without walking the graph themselves.
type LookupResult struct {
	Local              []LookupOrg `json:"local"`
	Query              LookupQuery `json:"query"`
	Regional           []LookupOrg `json:"regional"`
	ResolvedAncestry   []Region    `json:"resolved_ancestry"`
	ResolvedPlaceLabel string      `json:"resolved_place_label"`
}

// Meta Attribution block included on every collection response.
// Carries the ODbL license obligation in-band so consumers
// that strip headers still see the share-alike requirement.
type Meta struct {
	// AttributionUrl URL downstream consumers should link to when crediting
	// the source.
	AttributionUrl string `json:"attribution_url"`

	// GeneratedAt RFC 3339 timestamp recording when the response was
	// produced server-side. Per-request — there is no caching
	// layer in v1.
	GeneratedAt time.Time `json:"generated_at"`

	// License SPDX identifier of the data license. Stable for the
	// lifetime of v1 (`ODbL-1.0`).
	License string `json:"license"`
}

// NewSubmissionRequest Request body for `POST /api/v1/submissions`.
type NewSubmissionRequest struct {
	// Payload The proposed organization, as submitted by a member of the public.
	Payload SubmissionPayload `json:"payload"`

	// SubmitterEmail Optional. The submitter's contact email.
	SubmitterEmail *openapi_types.Email `json:"submitter_email,omitempty"`

	// SubmitterName Optional. The submitter's name.
	SubmitterName *string `json:"submitter_name,omitempty"`

	// SubmitterNote Optional. Free-form note to the moderators.
	SubmitterNote *string `json:"submitter_note,omitempty"`
}

// Org A single advocacy organization. `regions` is denormalized onto
// the organization for ergonomic JSON output — it lists every
// region the org serves, not just the regions that matched the
// current query.
type Org struct {
	// ContactUrl Optional. URL of the org's contact page.
	ContactUrl *string  `json:"contact_url,omitempty"`
	Id         int64    `json:"id"`
	Name       string   `json:"name"`
	Regions    []Region `json:"regions"`
	ShortDesc  string   `json:"short_desc"`
	Slug       string   `json:"slug"`

	// Tags Open-ended labels. The canonical set is documented in
	// `CLAUDE.md` (transit, safe-streets, cycling, walking,
	// vision-zero, policy, grassroots, political, neighborhood);
	// new labels may be introduced via seed data.
	Tags       []string `json:"tags"`
	WebsiteUrl string   `json:"website_url"`
}

// ProblemDetails Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type ProblemDetails struct {
	// Detail Human-readable explanation specific to this occurrence.
	// Safe to display to end users.
	Detail *string `json:"detail,omitempty"`

	// Errors Extension field. Per-field validation messages keyed by
	// JSON field name (e.g. `name`, `short_desc`,
	// `submitter_email`). Present only on validation failures
	// where multiple fields may be at fault — currently
	// `POST /api/v1/submissions`. Each value is a sentence safe
	// to render to end users; clients can dispatch them into
	// per-field form validators.
	Errors *map[string]string `json:"errors,omitempty"`

	// Instance URI reference that identifies the specific occurrence of
	// the problem — typically the request path.
	Instance *string `json:"instance,omitempty"`

	// RequestId Extension field. The server-side request ID; matches the
	// `X-Request-ID` response header. Useful for users to quote
	// when reporting bugs.
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP status code generated by the origin server. Mirrors
	// the response's status line; included in the body so it
	// survives proxies that mangle status codes.
	Status int32 `json:"status"`

	// Title Short, human-readable summary of the problem type. Should
	// not change between occurrences of the same problem type,
	// except for localization.
	Title string `json:"title"`

	// Type URI reference that identifies the problem type. When
	// absent or `about:blank`, the `title` alone identifies the
	// problem.
	Type string `json:"type"`
}

// RecentEnvelope Collection envelope for `GET /api/v1/recent`. Same shape
// contract as `RegionSummariesEnvelope`.
type RecentEnvelope struct {
	Data []Org `json:"data"`

	// Meta Attribution block included on every collection response.
	// Carries the ODbL license obligation in-band so consumers
	// that strip headers still see the share-alike requirement.
	Meta Meta `json:"meta"`
}

// Region A geographic unit an organization can serve. Regions form a
// directed acyclic graph; `parent_slugs` lists the direct parents
// (not transitive). Empty for top-of-hierarchy regions (states,
// multi-state regions, transit federations).
type Region struct {
	// Country ISO-style country code. v1 ships with `US` and `CA`; additional
	// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
	// changes as data is loaded.
	Country Country `json:"country"`
	Id      int64   `json:"id"`

	// Kind Free-form taxonomy for region granularity. The recommended
	// vocabulary uses country-prefixed values: `us:city`, `us:borough`,
	// `us:county`, `us:metro`, `us:state`, `us:multi-state`,
	// `us:transit-federation`, `ca:province`, `ca:regional-district`,
	// `ca:city`, `ca:cma`, `pt:freguesia`, `pt:municipio`,
	// `pt:cim`, `pt:area-metropolitana`, `pt:distrito`,
	// `pt:nuts-ii`, `pt:regiao-autonoma`, `pt:nacional`,
	// `de:land`, `de:bezirk`, `de:kreisfreie-stadt`,
	// `de:transit-federation`, `fr:commune`, `fr:departement`,
	// `fr:region`, `fr:metropole`. Clients should treat unknown kinds
	// gracefully (e.g. fall back to displaying `name`).
	Kind RegionKind `json:"kind"`
	Name string     `json:"name"`

	// ParentSlugs Direct parents in the region graph. Clients can walk these
	// to render breadcrumbs without a second request.
	ParentSlugs []string `json:"parent_slugs"`

	// ScopeTier Drives result grouping in `/lookup`. `local` for city/county
	// regions; `regional` for metro/state/province/multi-state;
	// `national` for country-wide umbrellas (federations, advocacy
	// groups operating across an entire country).
	//
	// `national` regions are filtered from the default `/lookup`
	// ancestor walk — they're present in the schema so that
	// national-scope orgs (e.g. MUBi for Portugal, Living Streets
	// for the UK) can be modeled without distorting local-first
	// defaults. A future opt-in surface for national orgs is
	// anticipated; until then, `national`-tier regions are hidden.
	//
	// See `docs/region-graph.md` for the per-country editorial
	// policy on when to use `national` vs modeling state/regional
	// chapters instead.
	ScopeTier ScopeTier `json:"scope_tier"`

	// Slug Globally unique across countries.
	Slug string `json:"slug"`
}

// RegionDetail A region (any non-national kind) with the organizations
// in scope for it, bucketed by attachment tier. "In scope"
// means orgs attached to the region itself or any DAG
// descendant — a metro surfaces its constituent cities'
// orgs, a state surfaces every metro/city beneath it.
// Ancestor orgs are NOT pulled in: this is "what does the
// region contain?", not "what works at this address?" (the
// latter is `/lookup`'s job, with its upward ancestor walk).
//
// Keeping the in-scope set descendant-only means the
// `RegionSummary.org_count` shown on the browse card matches
// the count delivered by this endpoint — no surprises when a
// user clicks through.
//
// Orgs are bucketed by the `scope_tier` of the attachment
// region they matched on — `local` for city/county-tier
// attachments, `regional` for metro/state/multi-state.
// `national`-tier attachments are always filtered.
//
// Each `LookupOrg.matched_region_slugs` names the
// attachment regions in scope that caused the org to
// surface — useful for "matched via X" affordances in
// clients.
//
// The `ancestry` array is the upward walk from this region
// to the root (closest-first, excluding self and any
// `scope_tier='national'` rows). Clients use it to render
// breadcrumbs.
//
// `descendant_region_names` is a slug → display-name map for
// every descendant region (city, borough, county, …) that an
// org in `local` or `regional` references via
// `matched_region_slugs`. Lets clients render
// "Matched via Brooklyn" instead of the raw slug
// "matched via brooklyn-ny" without a second request. The
// focus region's own slug and ancestry slugs are NOT included
// (clients seed those from `region` + `ancestry`). Empty
// object (`{}`) when no descendants need resolving.
type RegionDetail struct {
	// Ancestry Ancestors of `region`, ordered closest-first (the
	// region's direct parent at index 0, then the
	// grandparent, … up to the root). Excludes the region
	// itself and any `scope_tier='national'` rows.
	Ancestry []Region `json:"ancestry"`

	// DescendantRegionNames Slug → display-name lookup for descendant regions
	// referenced by `matched_region_slugs` in `local` or
	// `regional`. Excludes the focus region and its
	// ancestors (clients seed those from `region` and
	// `ancestry`). Empty object when no descendants need
	// resolving.
	DescendantRegionNames map[string]string `json:"descendant_region_names"`

	// Local Orgs in scope with at least one matched attachment
	// region of `scope_tier='local'` (cities, counties,
	// boroughs).
	Local []LookupOrg `json:"local"`

	// Region A geographic unit an organization can serve. Regions form a
	// directed acyclic graph; `parent_slugs` lists the direct parents
	// (not transitive). Empty for top-of-hierarchy regions (states,
	// multi-state regions, transit federations).
	Region Region `json:"region"`

	// Regional Orgs in scope whose only matched attachment regions
	// are `scope_tier='regional'` (metros, states,
	// provinces, multi-state coalitions).
	Regional []LookupOrg `json:"regional"`
}

// RegionKind Free-form taxonomy for region granularity. The recommended
// vocabulary uses country-prefixed values: `us:city`, `us:borough`,
// `us:county`, `us:metro`, `us:state`, `us:multi-state`,
// `us:transit-federation`, `ca:province`, `ca:regional-district`,
// `ca:city`, `ca:cma`, `pt:freguesia`, `pt:municipio`,
// `pt:cim`, `pt:area-metropolitana`, `pt:distrito`,
// `pt:nuts-ii`, `pt:regiao-autonoma`, `pt:nacional`,
// `de:land`, `de:bezirk`, `de:kreisfreie-stadt`,
// `de:transit-federation`, `fr:commune`, `fr:departement`,
// `fr:region`, `fr:metropole`. Clients should treat unknown kinds
// gracefully (e.g. fall back to displaying `name`).
type RegionKind = string

// RegionSummariesEnvelope Collection envelope for `GET /api/v1/regions`. Wraps the
// region list in a `meta` + `data` shape so every list
// response carries the ODbL attribution alongside its
// payload, even when transport-level headers are stripped.
type RegionSummariesEnvelope struct {
	Data []RegionSummary `json:"data"`

	// Meta Attribution block included on every collection response.
	// Carries the ODbL license obligation in-band so consumers
	// that strip headers still see the share-alike requirement.
	Meta Meta `json:"meta"`
}

// RegionSummary A region (any non-national kind) plus its approved-org counts.
// Used by `GET /api/v1/regions` to populate the Browse index.
//
// Two counts are exposed:
//
//   - `org_count` — distinct approved orgs attached to this region
//     OR any descendant in the DAG. Best for per-row "how much
//     coverage does this region have" displays (a metro's count
//     shows orgs from the metro + every city/borough/county
//     under it).
//   - `direct_org_count` — distinct approved orgs attached
//     DIRECTLY to this region (no descendant walk). Use this when
//     summing across rows in a country/page total: summing
//     `org_count` double-counts orgs that surface under both a
//     metro and one of its child cities.
type RegionSummary struct {
	// BrowseParentSlug For cities, the slug of the nearest ancestor in the
	// default browse set (a metro / CMA / regional-district).
	// Lets clients group cities visually under their parent
	// metro without a second request. Null for metros and for
	// standalone cities whose walk doesn't reach a browseable
	// ancestor.
	BrowseParentSlug *string `json:"browse_parent_slug,omitempty"`

	// DirectOrgCount Distinct approved orgs attached DIRECTLY to this region
	// (no descendant walk). Sums across rows yield a deduped
	// total.
	DirectOrgCount int32 `json:"direct_org_count"`

	// OrgCount Distinct approved orgs attached to this region OR any
	// descendant in the region DAG.
	OrgCount int32 `json:"org_count"`

	// Region A geographic unit an organization can serve. Regions form a
	// directed acyclic graph; `parent_slugs` lists the direct parents
	// (not transitive). Empty for top-of-hierarchy regions (states,
	// multi-state regions, transit federations).
	Region Region `json:"region"`
}

// RejectSubmissionRequest Request body for `POST /api/v1/admin/submissions/{id}/reject`.
type RejectSubmissionRequest struct {
	// Reason Free-form note shown to the submitter if email notifications are enabled, and persisted for audit.
	Reason string `json:"reason"`
}

// ScopeTier Drives result grouping in `/lookup`. `local` for city/county
// regions; `regional` for metro/state/province/multi-state;
// `national` for country-wide umbrellas (federations, advocacy
// groups operating across an entire country).
//
// `national` regions are filtered from the default `/lookup`
// ancestor walk — they're present in the schema so that
// national-scope orgs (e.g. MUBi for Portugal, Living Streets
// for the UK) can be modeled without distorting local-first
// defaults. A future opt-in surface for national orgs is
// anticipated; until then, `national`-tier regions are hidden.
//
// See `docs/region-graph.md` for the per-country editorial
// policy on when to use `national` vs modeling state/regional
// chapters instead.
type ScopeTier string

// Submission A queued or processed public submission.
type Submission struct {
	CreatedAt time.Time `json:"created_at"`

	// Id UUIDv7 string generated server-side when the submission was
	// accepted. This is the only ID exposed on the wire.
	Id openapi_types.UUID `json:"id"`

	// Payload The proposed organization, as submitted by a member of the public.
	Payload SubmissionPayload `json:"payload"`

	// ProcessedAt Set when status moves from `pending` to a terminal state.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	// PromotionError Set on approval when the GitHub PR worker failed (network,
	// auth, etc.). The submission stays `approved`; the PR is
	// re-queued via `urbanist-atlas-server submissions retry-pr`.
	PromotionError *string `json:"promotion_error,omitempty"`

	// PromotionPrUrl Set on approval when the GitHub PR worker successfully opens a
	// pull request appending the approved org to `api/seed/orgs.toml`.
	// The PR is the editorial-review surface; the org becomes visible
	// after a maintainer merges it and the API redeploys.
	PromotionPrUrl *string `json:"promotion_pr_url,omitempty"`

	// RejectionReason Set on rejection.
	RejectionReason *string `json:"rejection_reason,omitempty"`

	// Status Lifecycle state of a public submission.
	Status         SubmissionStatus     `json:"status"`
	SubmitterEmail *openapi_types.Email `json:"submitter_email,omitempty"`
	SubmitterName  *string              `json:"submitter_name,omitempty"`
	SubmitterNote  *string              `json:"submitter_note,omitempty"`
}

// SubmissionPayload The proposed organization, as submitted by a member of the public.
type SubmissionPayload struct {
	// ContactUrl Optional.
	ContactUrl *string `json:"contact_url,omitempty"`
	Name       string  `json:"name"`

	// RegionSlugs Optional. Slugs of the regions this organization serves
	// (e.g. `["brooklyn-ny","nyc-metro"]`). When provided, every
	// entry must resolve against the `regions` table at submit
	// time. May be omitted or sent as `[]` when the submitter
	// doesn't know the canonical slug — editors finalize the
	// region in PR review using `submitter_note`.
	RegionSlugs *[]string `json:"region_slugs,omitempty"`
	ShortDesc   string    `json:"short_desc"`
	Tags        []string  `json:"tags"`
	WebsiteUrl  string    `json:"website_url"`
}

// SubmissionStatus Lifecycle state of a public submission.
type SubmissionStatus string

// CountryQuery ISO-style country code. v1 ships with `US` and `CA`; additional
// countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
// changes as data is loaded.
type CountryQuery = Country

// PostalCodeQuery defines model for PostalCodeQuery.
type PostalCodeQuery = string

// RegionSlug defines model for RegionSlug.
type RegionSlug = string

// SubmissionID defines model for SubmissionID.
type SubmissionID = openapi_types.UUID

// BadRequest Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type BadRequest = ProblemDetails

// InternalError Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type InternalError = ProblemDetails

// NotFound Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type NotFound = ProblemDetails

// TooManyRequests Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type TooManyRequests = ProblemDetails

// Unauthorized Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
// Problem Details object. Returned on every non-2xx response with
// content-type `application/problem+json`.
//
// The `type` field is a stable URI identifying the problem class.
// The current v1 type values are:
//
//   - `https://urbanistatlas.com/problems/validation` — request was
//     malformed or missing a required field (HTTP 400).
//   - `https://urbanistatlas.com/problems/not-found` — the
//     requested resource does not exist (HTTP 404).
//   - `https://urbanistatlas.com/problems/unauthorized` — missing
//     or invalid bearer token on a protected endpoint (HTTP 401).
//   - `https://urbanistatlas.com/problems/conflict` — the requested
//     state transition is not valid given current state (e.g.
//     approving a non-pending submission) (HTTP 409).
//   - `https://urbanistatlas.com/problems/rate-limited` — too many
//     requests from this source (HTTP 429). A `Retry-After` header
//     is also returned.
//   - `https://urbanistatlas.com/problems/internal` — an
//     unexpected server error (HTTP 500).
//
// These URIs are stable identifiers; they do not necessarily
// dereference to a human-readable page yet.
//
// Additional fields beyond the RFC's standard five are permitted
// and consumers should ignore unknown fields. The `request_id`
// extension is included on every error response and matches the
// `X-Request-ID` response header so clients can quote it when
// reporting bugs.
type Unauthorized = ProblemDetails

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListSubmissionsParams defines parameters for ListSubmissions.
type ListSubmissionsParams struct {
	// Status Filter by submission status. Defaults to `pending`.
	Status *SubmissionStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Maximum number of submissions to return. Capped at 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination token. Pass the value of the previous
	// response's `X-Next-Cursor` header to fetch the next page.
	// Omit to start at the newest submission.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LookupParams defines parameters for Lookup.
type LookupParams struct {
	// PostalCode US ZIP code (e.g. `11217`) or Canadian postal code or FSA
	// (e.g. `M5V` or `M5V 3A8`). Whitespace is trimmed; CA codes are
	// truncated to their 3-character FSA server-side.
	PostalCode PostalCodeQuery `form:"postal_code" json:"postal_code"`

	// Country ISO-style country code. Case-insensitive.
	Country CountryQuery `form:"country" json:"country"`
}

// RejectSubmissionJSONRequestBody defines body for RejectSubmission for application/json ContentType.
type RejectSubmissionJSONRequestBody = RejectSubmissionRequest

// CreateSubmissionJSONRequestBody defines body for CreateSubmission for application/json ContentType.
type CreateSubmissionJSONRequestBody = NewSubmissionRequest
