/**
 * Typed HTTP client for the Urbanist Atlas API.
 *
 * All wire shapes (request/response bodies, enums, error envelopes) come
 * from `./api.gen.ts`, which is generated by `openapi-typescript` from
 * `../api/openapi.yaml`. Do not hand-roll types in this file — if you
 * need something new, add it to the spec and run `npm run generate:api`.
 *
 * The base URL is read from `import.meta.env.VITE_API_BASE` at build
 * time and defaults to the dev server URL. Set it in `.env.production`
 * (or via the Cloudflare Pages dashboard) for prod builds.
 */
import type { components } from './api.gen.ts';

// Re-export the wire shapes that callers will commonly touch, so they
// can `import { LookupResult } from '@/lib/api'` without reaching into
// the generated file directly.
export type Country = components['schemas']['Country'];
export type Region = components['schemas']['Region'];
export type Org = components['schemas']['Org'];
export type LookupOrg = components['schemas']['LookupOrg'];
export type LookupQuery = components['schemas']['LookupQuery'];
export type LookupResult = components['schemas']['LookupResult'];
export type RegionSummary = components['schemas']['RegionSummary'];
export type RegionSearchResult = components['schemas']['RegionSearchResult'];
export type RegionSearchResultsEnvelope =
  components['schemas']['RegionSearchResultsEnvelope'];
export type RegionDetail = components['schemas']['RegionDetail'];
export type Meta = components['schemas']['Meta'];
export type RegionSummariesEnvelope = components['schemas']['RegionSummariesEnvelope'];
export type RecentEnvelope = components['schemas']['RecentEnvelope'];
export type Submission = components['schemas']['Submission'];
export type SubmissionPayload = components['schemas']['SubmissionPayload'];
export type NewSubmissionRequest = components['schemas']['NewSubmissionRequest'];
export type ProblemDetails = components['schemas']['ProblemDetails'];

/**
 * Countries the SPA actively exposes to users. The wire `Country`
 * type is open (just `string` — the API accepts any code seed data
 * defines), but the UI is gated on this narrower set so a stray
 * `?country=…` value renders an error instead of silently coercing.
 * Bump this and SearchBox.tsx's `<select>` options together when a
 * new country goes user-facing.
 */
export const SUPPORTED_COUNTRIES = ['US', 'CA'] as const satisfies readonly Country[];

/** True if `raw` is one of {@link SUPPORTED_COUNTRIES}. */
export function isSupportedCountry(raw: string): raw is Country {
  return (SUPPORTED_COUNTRIES as readonly string[]).includes(raw);
}

const DEFAULT_API_BASE = 'http://localhost:8080';

/** Where the API lives. Set `VITE_API_BASE` to override at build time. */
export const apiBase: string = import.meta.env.VITE_API_BASE ?? DEFAULT_API_BASE;

/**
 * Shared secret bundled into the build during Phase 1 lockdown
 * (slice #23 / CLAUDE.md § Launch strategy). The backend's
 * `URBANIST_CLIENT_SECRET` checks for the matching `X-Atlas-Client`
 * header on every `/api/v1/*` data endpoint; missing/wrong → 401.
 *
 * Empty (the default for local dev when `VITE_API_CLIENT_SECRET`
 * isn't set) means the header isn't sent — the backend's empty-
 * secret no-op preserves the dev workflow.
 */
const apiClientSecret: string = import.meta.env.VITE_API_CLIENT_SECRET ?? '';

/**
 * Map of field name to human-readable error message, as returned by
 * the API in a problem+json `errors` extension on 400/422 responses.
 *
 * The current API only surfaces a top-level `detail` string (see
 * `internal/httpapi/submissions.go`), so this map will be `undefined`
 * in production today. Wired through ahead of a parallel pre-launch
 * API change that may add field-level errors; the SPA degrades to
 * the top-level `detail` when this is missing or empty.
 */
export type FieldErrors = Readonly<Record<string, string>>;

/**
 * Error thrown for any non-2xx response from the API. Carries the HTTP
 * status, the parsed RFC 9457 problem document (when the server sent
 * one), and the request ID for log correlation.
 *
 * Two extras lifted out of common headers / extensions:
 *   - {@link retryAfterSeconds}: parsed `Retry-After` (seconds or
 *     HTTP-date), used by the submission form to render a countdown
 *     after a 429.
 *   - {@link fieldErrors}: per-field validation errors when the
 *     problem+json envelope includes an `errors` extension. Falls
 *     back to top-level `detail` rendering at the call site when
 *     this is undefined.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly problem: ProblemDetails | undefined;
  readonly requestId: string | undefined;
  readonly retryAfterSeconds: number | undefined;
  readonly fieldErrors: FieldErrors | undefined;

  constructor(
    status: number,
    message: string,
    problem: ProblemDetails | undefined,
    requestId: string | undefined,
    extras?: {
      retryAfterSeconds?: number;
      fieldErrors?: FieldErrors;
    },
  ) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.problem = problem;
    this.requestId = requestId;
    this.retryAfterSeconds = extras?.retryAfterSeconds;
    this.fieldErrors = extras?.fieldErrors;
  }
}

/**
 * Parses a `Retry-After` header value into a non-negative number of
 * seconds. Accepts either the delta-seconds form (an integer) or an
 * HTTP-date (RFC 9110 §5.6.7); returns `undefined` for missing,
 * malformed, or past-dated values so callers can fall back to
 * static copy.
 *
 * Exported for direct testing; the `apiFetch` path attaches the
 * parsed value to `ApiError.retryAfterSeconds`.
 */
export function parseRetryAfter(
  header: string | null,
  now: () => number = Date.now,
): number | undefined {
  if (header === null) return undefined;
  const trimmed = header.trim();
  if (trimmed === '') return undefined;
  // Delta-seconds form: "120"
  if (/^\d+$/.test(trimmed)) {
    const n = Number.parseInt(trimmed, 10);
    return Number.isFinite(n) && n >= 0 ? n : undefined;
  }
  // HTTP-date form: "Wed, 21 Oct 2026 07:28:00 GMT"
  const t = Date.parse(trimmed);
  if (Number.isNaN(t)) return undefined;
  const delta = Math.ceil((t - now()) / 1000);
  return delta > 0 ? delta : 0;
}

/**
 * Best-effort extractor for per-field validation errors from a
 * problem+json envelope. Looks for an `errors` extension shaped as
 * `{ [field]: string }` (the convention this project will adopt if
 * the parallel API worktree adds it). Anything else returns
 * undefined and the caller falls back to top-level `detail`.
 */
function extractFieldErrors(
  problem: ProblemDetails | undefined,
): FieldErrors | undefined {
  if (!problem || typeof problem !== 'object') return undefined;
  const raw = (problem as { errors?: unknown }).errors;
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(raw)) {
    if (typeof k !== 'string' || k === '') continue;
    if (typeof v === 'string' && v !== '') out[k] = v;
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

/**
 * Low-level fetch wrapper. Prepends {@link apiBase} to `path`, sets
 * `Accept: application/json`, throws {@link ApiError} on non-2xx
 * responses (parsing `application/problem+json` bodies when present),
 * and returns the parsed JSON body as `T`.
 *
 * Callers should usually reach for a higher-level wrapper (e.g.
 * {@link lookup}) rather than calling this directly.
 */
export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const url = path.startsWith('http') ? path : `${apiBase}${path}`;
  const headers = new Headers(init?.headers);
  if (!headers.has('Accept')) {
    headers.set('Accept', 'application/json');
  }
  if (apiClientSecret && !headers.has('X-Atlas-Client')) {
    headers.set('X-Atlas-Client', apiClientSecret);
  }

  const response = await fetch(url, { ...init, headers });
  const requestId = response.headers.get('X-Request-ID') ?? undefined;

  if (!response.ok) {
    let problem: ProblemDetails | undefined;
    const contentType = response.headers.get('Content-Type') ?? '';
    if (contentType.includes('application/problem+json')) {
      try {
        problem = (await response.json()) as ProblemDetails;
      } catch {
        // Body wasn't valid JSON after all; ignore and fall through to a
        // bare-status error.
      }
    }
    const message = problem?.title ?? problem?.detail ?? `HTTP ${response.status}`;
    const retryAfterSeconds =
      response.status === 429
        ? parseRetryAfter(response.headers.get('Retry-After'))
        : undefined;
    const fieldErrors = extractFieldErrors(problem);
    throw new ApiError(response.status, message, problem, requestId, {
      retryAfterSeconds,
      fieldErrors,
    });
  }

  return (await response.json()) as T;
}

/**
 * `GET /api/v1/lookup?postal_code=…&country=…` — the main search.
 * Resolves to a {@link LookupResult} with `local` and `regional` orgs
 * for the postal code; throws {@link ApiError} on a non-2xx response
 * (including the 404 returned for unresolvable codes).
 */
export function lookup(
  postal_code: string,
  country: Country,
  init?: RequestInit,
): Promise<LookupResult> {
  const params = new URLSearchParams({ postal_code, country });
  return apiFetch<LookupResult>(`/api/v1/lookup?${params.toString()}`, init);
}

/**
 * `GET /api/v1/regions` — list the editorial default browse set
 * (metros + cities) with their approved-org counts. The endpoint
 * ships without filter parameters today; the right filter axis
 * (taxonomy via `kind`, DAG via `ancestor`, …) will be designed
 * when a concrete browse UI use case appears.
 *
 * The wire shape is `{ meta, data: RegionSummary[] }`; this helper
 * unwraps `data` so callers continue to receive the bare array.
 * Read `meta` (license, attribution_url, generated_at) by calling
 * `apiFetch<RegionSummariesEnvelope>` directly if you need it.
 */
export function listRegions(init?: RequestInit): Promise<RegionSummary[]> {
  return apiFetch<RegionSummariesEnvelope>('/api/v1/regions', init).then(
    (env) => env.data,
  );
}

/**
 * `GET /api/v1/regions/search?q=…&limit=…` — type-ahead search over
 * the full region graph (every kind, not just the browse set), ranked
 * for relevance. Each result carries a `context_label` (the nearest
 * state/province ancestor's name) for disambiguating same-named regions.
 *
 * The wire shape is `{ meta, data: RegionSearchResult[] }`; this helper
 * unwraps `data`. A blank `q` returns an empty array.
 */
export function searchRegions(
  q: string,
  limit?: number,
  init?: RequestInit,
): Promise<RegionSearchResult[]> {
  const params = new URLSearchParams({ q });
  if (limit !== undefined) params.set('limit', String(limit));
  return apiFetch<RegionSearchResultsEnvelope>(
    `/api/v1/regions/search?${params.toString()}`,
    init,
  ).then((env) => env.data);
}

/**
 * `GET /api/v1/regions/{slug}` — one region (any non-national kind)
 * plus the approved organizations that serve it (directly or via the
 * region DAG). Resolves metros, cities, counties, boroughs, states,
 * multi-state coalitions. Throws {@link ApiError} with status 404
 * when the slug is unknown or names a national-tier region.
 */
export function getRegion(slug: string, init?: RequestInit): Promise<RegionDetail> {
  return apiFetch<RegionDetail>(`/api/v1/regions/${encodeURIComponent(slug)}`, init);
}

/**
 * `GET /api/v1/orgs/{slug}` — one organization, with every region it
 * serves denormalized at `regions`. Throws {@link ApiError} with status
 * 404 when the slug isn't in the atlas (or names a non-approved org).
 *
 * Single-object response — no `{meta, data}` envelope. ODbL travels via
 * the `X-Data-License` + `X-Data-Attribution` response headers.
 */
export function getOrg(slug: string, init?: RequestInit): Promise<Org> {
  return apiFetch<Org>(`/api/v1/orgs/${encodeURIComponent(slug)}`, init);
}

/**
 * `GET /api/v1/recent` — recently approved organizations, newest
 * first. Feeds the homepage "Recently added" aside.
 *
 * The wire shape is `{ meta, data: Org[] }`; this helper unwraps
 * `data` so callers continue to receive the bare array.
 */
export function listRecent(init?: RequestInit): Promise<Org[]> {
  return apiFetch<RecentEnvelope>('/api/v1/recent', init).then((env) => env.data);
}

/**
 * `POST /api/v1/submissions` — queue an organization for editorial
 * review. The returned `Submission` carries the server-generated UUIDv7
 * `id` (echoed to the user as a short reference) and `status: 'pending'`.
 *
 * Validation errors come back as 400/422 problem documents; per-IP rate
 * limiting returns 429 with a `Retry-After` header. Callers handle the
 * three classes via `ApiError.status`.
 */
export function createSubmission(
  body: NewSubmissionRequest,
  init?: RequestInit,
): Promise<Submission> {
  const headers = new Headers(init?.headers);
  headers.set('Content-Type', 'application/json');
  return apiFetch<Submission>('/api/v1/submissions', {
    ...init,
    method: 'POST',
    headers,
    body: JSON.stringify(body),
  });
}
