/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe.
         * @description Used by Fly as a liveness check. Deliberately does NOT touch
         *     any downstream dependency (database, etc.) so a DB outage
         *     doesn't cause Fly to recycle the machine and lose the recovery
         *     window. Pair with `/readyz` for the downstream-aware probe.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe.
         * @description Returns 200 only when the data store is reachable (a 1-second
         *     store ping has succeeded). Returns 503 with an
         *     `application/problem+json` body (`type=https://urbanistatlas.com/problems/not-ready`)
         *     when the store is unavailable. Use this as the Fly readiness
         *     check so traffic stops routing to a machine that can't serve
         *     queries; keep `/healthz` as the liveness check so a transient
         *     downstream blip doesn't trigger a machine recycle.
         *
         *     The bundled in-memory FileStore currently has no out-of-process
         *     dependency to ping, so `/readyz` resolves to 200 as soon as the
         *     process is up. The probe stays in place so a future
         *     network-bound store implementation can opt in to the
         *     readiness gate without an API change.
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns this OpenAPI specification.
         * @description Lets external consumers discover the wire contract at runtime.
         *     The body is identical to the `api/openapi.yaml` file checked
         *     into the repo at the running binary's release.
         */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up advocacy organizations for a postal code.
         * @description Resolves the postal code to a set of geographic regions, then
         *     returns all approved organizations that serve any of those
         *     regions. Results are bucketed into `local` (city/county-level)
         *     and `regional` (metro/state/province/multi-state) groups, in
         *     that order of geographic specificity within each bucket.
         *
         *     Canadian postal codes are normalized to the 3-character FSA
         *     (e.g. `M5V 3A8` → `M5V`) server-side; clients may pass either
         *     form.
         *
         *     This is a single-object response — the body is a bare
         *     `LookupResult` with no `{meta, data}` envelope. ODbL
         *     attribution travels via the `X-Data-License` and
         *     `X-Data-Attribution` response headers (set on every
         *     `/api/v1/**` response), not an in-band `meta.license` field;
         *     the `meta` envelope is reserved for collection responses.
         */
        get: operations["lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List regions with approved organization counts.
         * @description Feeds the "Browse" panel on the home page. Returns the
         *     editorial default browse set — metros and cities — with at
         *     least one approved organization tagged to them directly or
         *     via the region DAG, plus an org count for each.
         *
         *     The region graph models global civic geography as a DAG —
         *     cities under metros, metros under multi-state regions, all
         *     of them with state/province edges where they apply. A
         *     ZIP-level lookup walks the graph **upward** (and partitions
         *     by scope_tier); this endpoint walks **downward** from each
         *     included region, so a metro's count includes orgs tagged to
         *     its constituent cities and boroughs. "Chicago Metro" and
         *     "Chicago" both appear, with the metro count strictly ≥ the
         *     city count.
         *
         *     `scope_tier='national'` regions are always excluded (the v1
         *     editorial decision; revisit when a national browse experience
         *     ships). The list endpoint deliberately ships without filter
         *     parameters; the right filter axis (taxonomy via `kind`, DAG
         *     via `ancestor`, etc.) will be designed when a concrete browse
         *     UI use case appears.
         *
         *     Pagination: v1 returns the whole list in a single response and
         *     will never default-truncate a today-complete result — a
         *     response without a cursor means you have every row. When
         *     pagination is introduced it will be additive and follow the
         *     same opaque-cursor convention as the admin `listSubmissions`
         *     endpoint: the response carries an `X-Next-Cursor` header (and
         *     an optional `meta.next_cursor`) when more rows exist beyond the
         *     current page; pass that value back as `?cursor=` to fetch the
         *     next page. The cursor format is undocumented and may change
         *     without notice — treat it as opaque. No `cursor` parameter is
         *     accepted yet.
         */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single region and the organizations that serve it.
         * @description Resolves any non-national region in the graph by slug — metros,
         *     cities, counties, boroughs, states/provinces, multi-state
         *     coalitions. Returns a `RegionDetail` with the focus region plus
         *     the orgs attached to it OR any DAG descendant, bucketed into
         *     `local` and `regional` by the `scope_tier` of each org's
         *     matched attachment region. Ancestor orgs are NOT pulled in —
         *     the city detail page is "what does Brooklyn contain?", not
         *     "what works at a Brooklyn address?" (the latter is `/lookup`'s
         *     job, with its upward walk). Keeping the in-scope set
         *     symmetric with `/api/v1/regions`'s descendant-walk `org_count`
         *     means the card's promised count matches this page's
         *     delivered count. `scope_tier='national'` slugs return 404
         *     (same v1 editorial gate as `/lookup` and the list endpoint).
         *
         *     `ancestry` carries the upward walk for breadcrumbs only — it
         *     does not affect org scope. `descendant_region_names` is a
         *     slug → display-name map covering every descendant region
         *     referenced by an org's `matched_region_slugs`, so clients can
         *     render "Matched via Brooklyn" instead of "matched via
         *     brooklyn-ny" without a second request.
         *
         *     This is a single-object response — the body is a bare
         *     `RegionDetail` with no `{meta, data}` envelope. ODbL
         *     attribution travels via the `X-Data-License` and
         *     `X-Data-Attribution` response headers (set on every
         *     `/api/v1/**` response), not an in-band `meta.license` field;
         *     the `meta` envelope is reserved for collection responses.
         *
         *     The `slug` you address here is a stable public identifier —
         *     once published it is appended-to, never renamed (see the
         *     `RegionSlug` parameter and `docs/region-graph.md`).
         */
        get: operations["getRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search regions by name or slug for type-ahead.
         * @description Case-insensitive search over the FULL region graph — every kind
         *     (boroughs, counties, cities, metros/CMAs, states/provinces,
         *     multi-state coalitions), not just the curated browse set that
         *     `GET /api/v1/regions` returns. Powers the region type-ahead on
         *     the public submission form so a submitter can attach an org to a
         *     canonical slug instead of free text.
         *
         *     Results are ranked for relevance — exact slug, then exact name,
         *     then name prefix, then slug prefix, then substring — with name
         *     ascending (then slug ascending) as the stable tiebreak. Each
         *     result carries a `context_label`: the nearest state/province
         *     ancestor's name (e.g. "New York" for `queens`), so the client
         *     can tell same-named leaves apart ("Springfield" in IL vs MA).
         *     The label is an empty string when no state ancestor resolves.
         *
         *     `scope_tier='national'` regions are always excluded (the same v1
         *     editorial gate as `/lookup` and the other browse endpoints). A
         *     blank or omitted `q` returns an empty `data` array rather than
         *     an error, so the client's empty-input state needs no special
         *     handling.
         *
         *     Wrapped in the standard `{ meta, data }` collection envelope.
         */
        get: operations["searchRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single organization by slug.
         * @description Returns the addressable detail view for one approved organization.
         *     The body is a bare `Org` — no `{meta, data}` envelope, since
         *     this is a single-object response; ODbL attribution travels via
         *     the `X-Data-License` and `X-Data-Attribution` response headers.
         */
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recently approved organizations.
         * @description Feeds the "Recently added" strip on the home page. Returns the
         *     most-recently-approved organizations across the whole atlas,
         *     newest first.
         *
         *     Pagination: v1 returns the whole list in a single response and
         *     will never default-truncate a today-complete result — a
         *     response without a cursor means you have every row. When
         *     pagination is introduced it will be additive and follow the
         *     same opaque-cursor convention as the admin `listSubmissions`
         *     endpoint: the response carries an `X-Next-Cursor` header (and
         *     an optional `meta.next_cursor`) when more rows exist beyond the
         *     current page; pass that value back as `?cursor=` to fetch the
         *     next page. The cursor format is undocumented and may change
         *     without notice — treat it as opaque. No `cursor` parameter is
         *     accepted yet.
         */
        get: operations["listRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a new organization for review.
         * @description Anyone can submit an organization. The submission lands in the
         *     moderation queue with `status: pending` and is reviewed by a
         *     maintainer before becoming visible in lookups. Rate-limited
         *     per source IP.
         */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending submissions.
         * @description Returns submissions in the moderation queue. By default returns
         *     only `pending` submissions; pass `status=approved` or
         *     `status=rejected` to view history. Results are newest-first
         *     with stable keyset pagination on `(created_at, id)`.
         *
         *     Pagination uses an opaque cursor. When more rows exist beyond
         *     the current page, the response carries an `X-Next-Cursor`
         *     header; pass that value back as `?cursor=` to fetch the next
         *     page. The cursor format is undocumented and may change without
         *     notice — treat it as opaque.
         */
        get: operations["listSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a submission and queue a promotion PR.
         * @description Marks the submission `approved` and enqueues an async GitHub PR
         *     that appends the new organization to `api/seed/orgs.toml`. The
         *     approval call returns as soon as the row is updated; the PR URL
         *     (or a `promotion_error`) is attached to the row when the worker
         *     finishes. If the worker failed, `urbanist-atlas-server
         *     submissions retry-pr --id=<uuid>` re-queues the job.
         */
        post: operations["approveSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a submission with a reason. */
        post: operations["rejectSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/coverage-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sampled empty-result lookups and searches.
         * @description Returns recent coverage gaps — sampled lookups and searches that
         *     resolved to no organizations. This is the editorial "which input
         *     returns nothing?" signal for deciding where to expand coverage.
         *
         *     Capture is sampled and row-capped server-side
         *     (`URBANIST_COVERAGE_SAMPLE_RATE` / `URBANIST_COVERAGE_MAX_ROWS`),
         *     so this is a recent, partial sample — not an exhaustive log.
         *     Results are newest-first.
         */
        get: operations["listCoverageGaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description ISO-style country code. v1 ships with `US` and `CA`; additional
         *     countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
         *     changes as data is loaded.
         * @example US
         */
        Country: string;
        /**
         * @description One sampled empty-result lookup or search — an editorial signal
         *     of where the directory has no coverage yet. Admin-only; capture
         *     is sampled, so the set is a recent partial sample.
         */
        CoverageGap: {
            /**
             * @description `lookup` — a postal-code lookup that resolved a region but
             *     surfaced no organizations. `search` — a region type-ahead
             *     query that matched nothing.
             * @enum {string}
             */
            kind: "lookup" | "search";
            /**
             * @description Lookup country (e.g. `US`, `CA`). Empty/omitted for `search`
             *     gaps, which have no country axis.
             * @example US
             */
            country?: string;
            /**
             * @description The normalized postal code (`lookup`) or the search query
             *     (`search`) that returned nothing.
             */
            input: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when the gap was recorded.
             */
            created_at: string;
        };
        /**
         * @description Attribution block included on every collection response.
         *     Carries the ODbL license obligation in-band so consumers
         *     that strip headers still see the share-alike requirement.
         */
        Meta: {
            /**
             * @description SPDX identifier of the data license. Stable for the
             *     lifetime of v1 (`ODbL-1.0`).
             * @example ODbL-1.0
             */
            license: string;
            /**
             * Format: uri
             * @description URL downstream consumers should link to when crediting
             *     the source.
             * @example https://urbanistatlas.com
             */
            attribution_url: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp recording when the response was
             *     produced server-side. Per-request — there is no caching
             *     layer in v1.
             * @example 2026-05-18T12:34:56Z
             */
            generated_at: string;
            /**
             * @description Reserved for future pagination. Optional and absent in v1:
             *     collection endpoints return the whole list in a single
             *     response today. When present (a future additive change), it
             *     mirrors the `X-Next-Cursor` response header — an opaque
             *     token to pass back as `?cursor=` for the next page. Treat as
             *     opaque; the format may change without notice. Its absence
             *     always means there are no further rows.
             */
            next_cursor?: string;
        };
        /**
         * @description Drives result grouping in `/lookup`. `local` for city/county
         *     regions; `regional` for metro/state/province/multi-state;
         *     `national` for country-wide umbrellas (federations, advocacy
         *     groups operating across an entire country).
         *
         *     `national` regions are filtered from the default `/lookup`
         *     ancestor walk — they're present in the schema so that
         *     national-scope orgs (e.g. MUBi for Portugal, Living Streets
         *     for the UK) can be modeled without distorting local-first
         *     defaults. A future opt-in surface for national orgs is
         *     anticipated; until then, `national`-tier regions are hidden.
         *
         *     See `docs/region-graph.md` for the per-country editorial
         *     policy on when to use `national` vs modeling state/regional
         *     chapters instead.
         *
         *     Treat this as an open enum: although v1 ships exactly
         *     `local`, `regional`, and `national`, consumers should ignore
         *     unknown values rather than failing if a future tier is added
         *     (do not exhaustively switch and error on the default case).
         *     The enumerated set may grow without a breaking-change bump.
         * @enum {string}
         */
        ScopeTier: "local" | "regional" | "national";
        /**
         * @description Free-form taxonomy for region granularity. The recommended
         *     vocabulary uses country-prefixed values: `us:city`, `us:borough`,
         *     `us:county`, `us:metro`, `us:state`, `us:multi-state`,
         *     `us:transit-federation`, `ca:province`, `ca:regional-district`,
         *     `ca:city`, `ca:cma`, `pt:freguesia`, `pt:municipio`,
         *     `pt:cim`, `pt:area-metropolitana`, `pt:distrito`,
         *     `pt:nuts-ii`, `pt:regiao-autonoma`, `pt:nacional`,
         *     `de:land`, `de:bezirk`, `de:kreisfreie-stadt`,
         *     `de:transit-federation`, `fr:commune`, `fr:departement`,
         *     `fr:region`, `fr:metropole`. Clients should treat unknown kinds
         *     gracefully (e.g. fall back to displaying `name`).
         * @example us:metro
         */
        RegionKind: string;
        /**
         * @description Lifecycle state of a public submission.
         * @enum {string}
         */
        SubmissionStatus: "pending" | "approved" | "rejected";
        /**
         * @description A geographic unit an organization can serve. Regions form a
         *     directed acyclic graph; `parent_slugs` lists the direct parents
         *     (not transitive). Empty for top-of-hierarchy regions (states,
         *     multi-state regions, transit federations).
         */
        Region: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["RegionKind"];
            /** @example Brooklyn */
            name: string;
            /**
             * @description Globally unique across countries.
             * @example brooklyn
             */
            slug: string;
            country: components["schemas"]["Country"];
            scope_tier: components["schemas"]["ScopeTier"];
            /**
             * @description Direct parents in the region graph. Clients can walk these
             *     to render breadcrumbs without a second request.
             */
            parent_slugs: string[];
        };
        /**
         * @description A single advocacy organization. `regions` is denormalized onto
         *     the organization for ergonomic JSON output — it lists every
         *     region the org serves, not just the regions that matched the
         *     current query.
         */
        Org: {
            /** Format: int64 */
            id: number;
            /** @example transalt */
            slug: string;
            /** @example Transportation Alternatives */
            name: string;
            /** @example NYC-wide advocacy for walking, biking, and public transit. */
            short_desc: string;
            /**
             * Format: uri
             * @example https://www.transalt.org
             */
            website_url: string;
            /**
             * Format: uri
             * @description Optional. URL of the org's contact page.
             */
            contact_url?: string;
            /**
             * @description Open-ended labels. The canonical set is documented in
             *     `CLAUDE.md` (transit, safe-streets, cycling, walking,
             *     vision-zero, policy, grassroots, political, neighborhood);
             *     new labels may be introduced via seed data.
             */
            tags: string[];
            /**
             * @description Every region this org serves, denormalized. Unordered —
             *     address regions by `slug`, not by position. Any apparent
             *     ordering is a process-internal handle (the loader sorts by
             *     a synthetic, load-order-assigned ID that is not stable
             *     across deploys), not a stable identifier; do not depend on
             *     it.
             */
            regions: components["schemas"]["Region"][];
            /**
             * Format: date
             * @description Date the org was added to the atlas. Date-only (no time
             *     component). Sourced from the seed file's `added_at` field
             *     on import, and from the approval date for orgs added via
             *     the submission queue. Drives the homepage "Recently
             *     indexed" strip's newest-first ordering.
             * @example 2026-05-21
             */
            added_at: string;
        };
        /**
         * @description An `Org` augmented with the per-lookup `matched_region_slugs`
         *     field. Returned only by `/api/v1/lookup`; other endpoints that
         *     return organizations use the base `Org` schema.
         */
        LookupOrg: components["schemas"]["Org"] & {
            /**
             * @description Slugs of the regions whose membership caused this org
             *     to surface for the current lookup. A non-empty subset
             *     of the org's `regions[*].slug`. Useful for
             *     explainability and debugging.
             */
            matched_region_slugs: string[];
        };
        LookupQuery: {
            /** @example 11217 */
            postal_code: string;
            country: components["schemas"]["Country"];
        };
        /**
         * @description Response shape of `GET /api/v1/lookup`. `local`, `regional`,
         *     and `statewide` are always present (possibly empty arrays).
         *     Orgs are bucketed by the scope_tier and kind of the attachment
         *     region they matched on: `local` for city/county-tier
         *     attachments; `statewide` for state/province-tier attachments
         *     (`us:state`, `ca:province`); `regional` for everything in
         *     between (metro/CMA/regional-district/transit-federation and
         *     multi-state coalitions). `national`-tier attachments are always
         *     filtered.
         *     `resolved_ancestry` is the postal code's leaf region followed
         *     by all ancestors, ordered most-specific first — clients can use
         *     it to render breadcrumbs without walking the graph themselves.
         */
        LookupResult: {
            query: components["schemas"]["LookupQuery"];
            /** @example Brooklyn, NYC — New York Metro */
            resolved_place_label: string;
            resolved_ancestry: components["schemas"]["Region"][];
            /**
             * @description Orgs with at least one matched attachment region of
             *     `scope_tier='local'` (cities, counties, boroughs).
             */
            local: components["schemas"]["LookupOrg"][];
            /**
             * @description Orgs whose matched attachment regions are sub-state
             *     `scope_tier='regional'` (metros, CMAs, regional districts,
             *     transit federations, multi-state coalitions) with no
             *     local or state/province match.
             */
            regional: components["schemas"]["LookupOrg"][];
            /**
             * @description Orgs whose matched attachment regions include a
             *     state/province-tier region (`us:state`, `ca:province`)
             *     and no `local` match. Surfaced as a distinct "State /
             *     Provincial" section so statewide coalitions don't blur
             *     into metro-level groups.
             */
            statewide: components["schemas"]["LookupOrg"][];
        };
        /**
         * @description A region (any non-national kind) plus its approved-org counts.
         *     Used by `GET /api/v1/regions` to populate the Browse index.
         *
         *     Two counts are exposed:
         *
         *     * `org_count` — distinct approved orgs attached to this region
         *       OR any descendant in the DAG. Best for per-row "how much
         *       coverage does this region have" displays (a metro's count
         *       shows orgs from the metro + every city/borough/county
         *       under it).
         *     * `direct_org_count` — distinct approved orgs attached
         *       DIRECTLY to this region (no descendant walk). Use this when
         *       summing across rows in a country/page total: summing
         *       `org_count` double-counts orgs that surface under both a
         *       metro and one of its child cities.
         */
        RegionSummary: {
            region: components["schemas"]["Region"];
            /**
             * Format: int32
             * @description Distinct approved orgs attached to this region OR any
             *     descendant in the region DAG.
             */
            org_count: number;
            /**
             * Format: int32
             * @description Distinct approved orgs attached DIRECTLY to this region
             *     (no descendant walk). Sums across rows yield a deduped
             *     total.
             */
            direct_org_count: number;
            /**
             * @description For cities, the slug of the nearest ancestor in the
             *     default browse set (a metro / CMA / regional-district).
             *     Lets clients group cities visually under their parent
             *     metro without a second request. Null for metros and for
             *     standalone cities whose walk doesn't reach a browseable
             *     ancestor.
             * @example chicago-metro
             */
            browse_parent_slug?: string | null;
        };
        /**
         * @description A region (any non-national kind) with the organizations
         *     in scope for it, bucketed by attachment tier. "In scope"
         *     means orgs attached to the region itself or any DAG
         *     descendant — a metro surfaces its constituent cities'
         *     orgs, a state surfaces every metro/city beneath it.
         *     Ancestor orgs are NOT pulled in: this is "what does the
         *     region contain?", not "what works at this address?" (the
         *     latter is `/lookup`'s job, with its upward ancestor walk).
         *
         *     Keeping the in-scope set descendant-only means the
         *     `RegionSummary.org_count` shown on the browse card matches
         *     the count delivered by this endpoint — no surprises when a
         *     user clicks through.
         *
         *     Orgs are bucketed by the `scope_tier` and kind of the
         *     attachment region they matched on — `local` for city/county-tier
         *     attachments, `statewide` for state/province-tier attachments
         *     (`us:state`, `ca:province`), `regional` for the sub-state middle
         *     (metro/CMA/regional-district/transit-federation/multi-state).
         *     `national`-tier attachments are always filtered.
         *
         *     Each `LookupOrg.matched_region_slugs` names the
         *     attachment regions in scope that caused the org to
         *     surface — useful for "matched via X" affordances in
         *     clients.
         *
         *     The `ancestry` array is the upward walk from this region
         *     to the root (closest-first, excluding self and any
         *     `scope_tier='national'` rows). Clients use it to render
         *     breadcrumbs.
         *
         *     `descendant_region_names` is a slug → display-name map for
         *     every descendant region (city, borough, county, …) that an
         *     org in `local` or `regional` references via
         *     `matched_region_slugs`. Lets clients render
         *     "Matched via Brooklyn" instead of the raw slug
         *     "matched via brooklyn-ny" without a second request. The
         *     focus region's own slug and ancestry slugs are NOT included
         *     (clients seed those from `region` + `ancestry`). Empty
         *     object (`{}`) when no descendants need resolving.
         */
        RegionDetail: {
            region: components["schemas"]["Region"];
            /**
             * @description Orgs in scope with at least one matched attachment
             *     region of `scope_tier='local'` (cities, counties,
             *     boroughs).
             */
            local: components["schemas"]["LookupOrg"][];
            /**
             * @description Orgs in scope whose matched attachment regions are
             *     sub-state `scope_tier='regional'` (metros, CMAs, regional
             *     districts, transit federations, multi-state coalitions),
             *     with no local or state/province match.
             */
            regional: components["schemas"]["LookupOrg"][];
            /**
             * @description Orgs in scope whose matched attachment regions include a
             *     state/province-tier region (`us:state`, `ca:province`)
             *     and no `local` match.
             */
            statewide: components["schemas"]["LookupOrg"][];
            /**
             * @description Ancestors of `region`, ordered closest-first (the
             *     region's direct parent at index 0, then the
             *     grandparent, … up to the root). Excludes the region
             *     itself and any `scope_tier='national'` rows.
             */
            ancestry: components["schemas"]["Region"][];
            /**
             * @description Slug → display-name lookup for descendant regions
             *     referenced by `matched_region_slugs` in `local`,
             *     `regional`, or `statewide`. Excludes the focus region and its
             *     ancestors (clients seed those from `region` and
             *     `ancestry`). Empty object when no descendants need
             *     resolving.
             * @example {
             *       "brooklyn-ny": "Brooklyn",
             *       "kings-county-ny": "Kings County, NY"
             *     }
             */
            descendant_region_names: {
                [key: string]: string;
            };
        };
        /**
         * @description Collection envelope for `GET /api/v1/regions`. Wraps the
         *     region list in a `meta` + `data` shape so every list
         *     response carries the ODbL attribution alongside its
         *     payload, even when transport-level headers are stripped.
         */
        RegionSummariesEnvelope: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["RegionSummary"][];
        };
        /**
         * @description A region matched by `GET /api/v1/regions/search`, plus a
         *     disambiguation hint for type-ahead display.
         */
        RegionSearchResult: {
            region: components["schemas"]["Region"];
            /**
             * @description The nearest state/province-equivalent ancestor's name (e.g.
             *     "New York" for the `queens` borough), to disambiguate
             *     same-named regions in a type-ahead. Empty string when the
             *     region has no resolvable state ancestor (a state itself, or
             *     a top-level region).
             * @example New York
             */
            context_label: string;
        };
        /**
         * @description Collection envelope for `GET /api/v1/regions/search`. Same shape
         *     contract as `RegionSummariesEnvelope`.
         */
        RegionSearchResultsEnvelope: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["RegionSearchResult"][];
        };
        /**
         * @description Collection envelope for `GET /api/v1/recent`. Same shape
         *     contract as `RegionSummariesEnvelope`.
         */
        RecentEnvelope: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["Org"][];
        };
        /**
         * @description The proposed organization, as submitted by a member of the
         *     public. There is no `tags` field: the public form doesn't
         *     collect tags — an editor assigns them while reviewing the
         *     promotion PR, so they aren't part of the submission wire shape.
         */
        SubmissionPayload: {
            name: string;
            short_desc: string;
            /** Format: uri */
            website_url: string;
            /**
             * Format: uri
             * @description Optional.
             */
            contact_url?: string;
            /**
             * @description Optional. Slugs of the regions this organization serves
             *     (e.g. `["brooklyn-ny","nyc-metro"]`). When provided, every
             *     entry must resolve against the `regions` table at submit
             *     time. May be omitted or sent as `[]` when the submitter
             *     doesn't know the canonical slug — editors finalize the
             *     region in PR review using `submitter_note`.
             */
            region_slugs?: string[];
        };
        /** @description Request body for `POST /api/v1/submissions`. */
        NewSubmissionRequest: {
            payload: components["schemas"]["SubmissionPayload"];
            /** @description Optional. The submitter's name. */
            submitter_name?: string;
            /**
             * Format: email
             * @description Optional. The submitter's contact email.
             */
            submitter_email?: string;
            /** @description Optional. Free-form note to the moderators. */
            submitter_note?: string;
        };
        /** @description A queued or processed public submission. */
        Submission: {
            /**
             * Format: uuid
             * @description UUIDv7 string generated server-side when the submission was
             *     accepted. This is the only ID exposed on the wire.
             */
            id: string;
            payload: components["schemas"]["SubmissionPayload"];
            submitter_name?: string;
            /** Format: email */
            submitter_email?: string;
            submitter_note?: string;
            status: components["schemas"]["SubmissionStatus"];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Set when status moves from `pending` to a terminal state.
             */
            processed_at?: string;
            /**
             * Format: uri
             * @description Set on approval when the GitHub PR worker successfully opens a
             *     pull request appending the approved org to `api/seed/orgs.toml`.
             *     The PR is the editorial-review surface; the org becomes visible
             *     after a maintainer merges it and the API redeploys.
             */
            promotion_pr_url?: string;
            /**
             * @description Set on approval when the GitHub PR worker failed (network,
             *     auth, etc.). The submission stays `approved`; the PR is
             *     re-queued via `urbanist-atlas-server submissions retry-pr`.
             */
            promotion_error?: string;
            /** @description Set on rejection. */
            rejection_reason?: string;
        };
        /** @description Request body for `POST /api/v1/admin/submissions/{id}/reject`. */
        RejectSubmissionRequest: {
            /** @description Free-form note shown to the submitter if email notifications are enabled, and persisted for audit. */
            reason: string;
        };
        /**
         * @description Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
         *     Problem Details object. Returned on every non-2xx response with
         *     content-type `application/problem+json`.
         *
         *     The `type` field is a stable URI identifying the problem class.
         *     The current v1 type values are:
         *
         *     - `https://urbanistatlas.com/problems/validation` — request was
         *       malformed or missing a required field (HTTP 400).
         *     - `https://urbanistatlas.com/problems/not-found` — the
         *       requested resource does not exist (HTTP 404).
         *     - `https://urbanistatlas.com/problems/unauthorized` — missing
         *       or invalid bearer token on a protected endpoint (HTTP 401).
         *     - `https://urbanistatlas.com/problems/conflict` — the requested
         *       state transition is not valid given current state (e.g.
         *       approving a non-pending submission) (HTTP 409).
         *     - `https://urbanistatlas.com/problems/rate-limited` — too many
         *       requests from this source (HTTP 429). A `Retry-After` header
         *       is also returned.
         *     - `https://urbanistatlas.com/problems/internal` — an
         *       unexpected server error (HTTP 500).
         *
         *     These URIs are stable identifiers; they do not necessarily
         *     dereference to a human-readable page yet.
         *
         *     Additional fields beyond the RFC's standard five are permitted
         *     and consumers should ignore unknown fields. The `request_id`
         *     extension is included on every error response and matches the
         *     `X-Request-ID` response header so clients can quote it when
         *     reporting bugs.
         * @example {
         *       "type": "https://urbanistatlas.com/problems/not-found",
         *       "title": "Postal code not found",
         *       "status": 404,
         *       "detail": "No region is mapped to postal code 00000 (US).",
         *       "instance": "/api/v1/lookup",
         *       "request_id": "a1b2c3d4e5f6g7h8"
         *     }
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI reference that identifies the problem type. When
             *     absent or `about:blank`, the `title` alone identifies the
             *     problem.
             * @default about:blank
             * @example https://urbanistatlas.com/problems/validation
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem type. Should
             *     not change between occurrences of the same problem type,
             *     except for localization.
             * @example Bad Request
             */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code generated by the origin server. Mirrors
             *     the response's status line; included in the body so it
             *     survives proxies that mangle status codes.
             * @example 400
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             *     Safe to display to end users.
             * @example postal_code is required
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference that identifies the specific occurrence of
             *     the problem — typically the request path.
             * @example /api/v1/lookup
             */
            instance?: string;
            /**
             * @description Extension field. The server-side request ID; matches the
             *     `X-Request-ID` response header. Useful for users to quote
             *     when reporting bugs.
             * @example a1b2c3d4e5f6g7h8
             */
            request_id?: string;
            /**
             * @description Extension field. Per-field validation messages keyed by
             *     JSON field name (e.g. `name`, `short_desc`,
             *     `submitter_email`). Present only on validation failures
             *     where multiple fields may be at fault — currently
             *     `POST /api/v1/submissions`. Each value is a sentence safe
             *     to render to end users; clients can dispatch them into
             *     per-field form validators.
             * @example {
             *       "short_desc": "A short description is required.",
             *       "website_url": "Website URL must use http or https."
             *     }
             */
            errors?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /**
         * @description Request was malformed or missing required parameters.
         *     Response body is an RFC 9457 problem document with
         *     `type` typically `https://urbanistatlas.com/problems/validation`.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Authentication failed. Either the request omitted required
         *     auth (missing `X-Atlas-Client` header during the Phase 1
         *     dogfooding lockdown, or missing `Authorization` bearer on an
         *     admin endpoint), or the presented value was invalid.
         *     Response body is an RFC 9457 problem document with
         *     `type` `https://urbanistatlas.com/problems/unauthorized`.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description The requested resource was not found.
         *     Response body is an RFC 9457 problem document with
         *     `type` `https://urbanistatlas.com/problems/not-found`.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Rate limit exceeded. Includes a `Retry-After` header.
         *     Response body is an RFC 9457 problem document with
         *     `type` `https://urbanistatlas.com/problems/rate-limited`.
         */
        TooManyRequests: {
            headers: {
                /** @description Seconds the client should wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description An unexpected server error occurred. The `request_id`
         *     extension field (and the `X-Request-ID` response header)
         *     identify the request in server logs.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /**
         * @description US ZIP code (e.g. `11217`) or Canadian postal code or FSA
         *     (e.g. `M5V` or `M5V 3A8`). Whitespace is trimmed; CA codes are
         *     truncated to their 3-character FSA server-side.
         */
        PostalCodeQuery: string;
        /** @description ISO-style country code. Case-insensitive. */
        CountryQuery: components["schemas"]["Country"];
        /**
         * @description Any non-national region's slug. Examples: `nyc-metro` (metro),
         *     `chicago` (city), `cook-county` (county), `chicagoland`
         *     (multi-state region), `ny` (state), `toronto-cma`
         *     (Canadian CMA), `metro-vancouver` (regional district).
         *
         *     Slugs are stable public identifiers. Once a slug is published
         *     it is appended-to, never renamed — a published slug will not
         *     change out from under a bookmark or an external consumer.
         *     Curated and override-pinned slugs are fully stable;
         *     auto-generated MSA/CMA slugs can in principle shift on an
         *     upstream-vintage bump and are pinned via the override file when
         *     that matters. See `docs/region-graph.md` for the contributor
         *     append-not-rename rule and the stable-vs-volatile split.
         */
        RegionSlug: string;
        /**
         * @description The submission's public ID — a UUIDv7 string generated when the
         *     row was created. The numeric storage ID is never exposed.
         */
        SubmissionID: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description SPDX identifier of the dataset license. Stable for the
         *     lifetime of v1.
         */
        XDataLicense: string;
        /**
         * @description URL downstream consumers should link to when crediting
         *     the source.
         */
        XDataAttribution: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service can serve queries (store is reachable). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Service is up but the data store is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3 specification, in YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    lookup: {
        parameters: {
            query: {
                /**
                 * @description US ZIP code (e.g. `11217`) or Canadian postal code or FSA
                 *     (e.g. `M5V` or `M5V 3A8`). Whitespace is trimmed; CA codes are
                 *     truncated to their 3-character FSA server-side.
                 */
                postal_code: components["parameters"]["PostalCodeQuery"];
                /** @description ISO-style country code. Case-insensitive. */
                country: components["parameters"]["CountryQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lookup succeeded. */
            200: {
                headers: {
                    "X-Data-License": components["headers"]["XDataLicense"];
                    "X-Data-Attribution": components["headers"]["XDataAttribution"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Regions with counts, ordered by org count descending then
             *     name ascending. Wrapped in a `{ meta, data }` envelope;
             *     the `RegionSummary[]` lives at `data`.
             */
            200: {
                headers: {
                    "X-Data-License": components["headers"]["XDataLicense"];
                    "X-Data-Attribution": components["headers"]["XDataAttribution"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionSummariesEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Any non-national region's slug. Examples: `nyc-metro` (metro),
                 *     `chicago` (city), `cook-county` (county), `chicagoland`
                 *     (multi-state region), `ny` (state), `toronto-cma`
                 *     (Canadian CMA), `metro-vancouver` (regional district).
                 *
                 *     Slugs are stable public identifiers. Once a slug is published
                 *     it is appended-to, never renamed — a published slug will not
                 *     change out from under a bookmark or an external consumer.
                 *     Curated and override-pinned slugs are fully stable;
                 *     auto-generated MSA/CMA slugs can in principle shift on an
                 *     upstream-vintage bump and are pinned via the override file when
                 *     that matters. See `docs/region-graph.md` for the contributor
                 *     append-not-rename rule and the stable-vs-volatile split.
                 */
                slug: components["parameters"]["RegionSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The region and its descendant organizations. */
            200: {
                headers: {
                    "X-Data-License": components["headers"]["XDataLicense"];
                    "X-Data-Attribution": components["headers"]["XDataAttribution"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchRegions: {
        parameters: {
            query?: {
                /**
                 * @description The search term. Matched case-insensitively against region
                 *     name and slug. Blank, whitespace-only, or omitted returns an
                 *     empty result set.
                 */
                q?: string;
                /** @description Maximum number of results to return. Capped at 20. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Matching regions, ranked by relevance. Wrapped in a
             *     `{ meta, data }` envelope; the `RegionSearchResult[]` lives
             *     at `data`.
             */
            200: {
                headers: {
                    "X-Data-License": components["headers"]["XDataLicense"];
                    "X-Data-Attribution": components["headers"]["XDataAttribution"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionSearchResultsEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example transportation-alternatives */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization, with every region it serves denormalized at `regions`. */
            200: {
                headers: {
                    "X-Data-License": components["headers"]["XDataLicense"];
                    "X-Data-Attribution": components["headers"]["XDataAttribution"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRecent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Recently approved organizations. Wrapped in a
             *     `{ meta, data }` envelope; the `Org[]` lives at `data`.
             */
            200: {
                headers: {
                    "X-Data-License": components["headers"]["XDataLicense"];
                    "X-Data-Attribution": components["headers"]["XDataAttribution"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission accepted into the queue. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listSubmissions: {
        parameters: {
            query?: {
                /** @description Filter by submission status. Defaults to `pending`. */
                status?: components["schemas"]["SubmissionStatus"];
                /** @description Maximum number of submissions to return. Capped at 200. */
                limit?: number;
                /**
                 * @description Opaque pagination token. Pass the value of the previous
                 *     response's `X-Next-Cursor` header to fetch the next page.
                 *     Omit to start at the newest submission.
                 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submissions matching the filter, newest first. */
            200: {
                headers: {
                    /**
                     * @description Opaque cursor for the next page. Present only when more
                     *     rows exist beyond the current page.
                     */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    approveSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The submission's public ID — a UUIDv7 string generated when the
                 *     row was created. The numeric storage ID is never exposed.
                 */
                id: components["parameters"]["SubmissionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Submission approved. The returned record may already include
             *     `promotion_pr_url` or `promotion_error` if the worker
             *     finished synchronously.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Submission is not in `pending` state.
             *     Response body is an RFC 9457 problem document with
             *     `type` `https://urbanistatlas.com/problems/conflict`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    rejectSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The submission's public ID — a UUIDv7 string generated when the
                 *     row was created. The numeric storage ID is never exposed.
                 */
                id: components["parameters"]["SubmissionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission rejected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Submission is not in `pending` state.
             *     Response body is an RFC 9457 problem document with
             *     `type` `https://urbanistatlas.com/problems/conflict`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listCoverageGaps: {
        parameters: {
            query?: {
                /** @description Maximum number of coverage gaps to return. Capped at 200. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent coverage gaps, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageGap"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
}
