/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe.
         * @description Used by Fly's health checks. Deliberately does not touch any
         *     downstream dependency (database, etc.) so it stays cheap and
         *     predictable.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns this OpenAPI specification.
         * @description Lets external consumers discover the wire contract at runtime.
         *     The body is identical to the `api/openapi.yaml` file checked
         *     into the repo at the running binary's release.
         */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up advocacy organizations for a postal code.
         * @description Resolves the postal code to a set of geographic regions, then
         *     returns all approved organizations that serve any of those
         *     regions. Results are bucketed into `local` (city/county-level)
         *     and `regional` (metro/state/province/multi-state) groups, in
         *     that order of geographic specificity within each bucket.
         *
         *     Canadian postal codes are normalized to the 3-character FSA
         *     (e.g. `M5V 3A8` → `M5V`) server-side; clients may pass either
         *     form.
         */
        get: operations["lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List metros with approved organization counts.
         * @description Feeds the "Browse by metro" panel on the home page. Returns
         *     every region of kind `metro` that has at least one approved
         *     organization tagged to it, with a count.
         */
        get: operations["listMetros"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metros/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approved organizations in a single metro. */
        get: operations["getMetro"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recently approved organizations.
         * @description Feeds the "Recently added" strip on the home page. Returns the
         *     most-recently-approved organizations across the whole atlas,
         *     newest first.
         */
        get: operations["listRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a new organization for review.
         * @description Anyone can submit an organization. The submission lands in the
         *     moderation queue with `status: pending` and is reviewed by a
         *     maintainer before becoming visible in lookups. Rate-limited
         *     per source IP.
         */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending submissions.
         * @description Returns submissions in the moderation queue. By default returns
         *     only `pending` submissions; pass `status=approved` or
         *     `status=rejected` to view history.
         */
        get: operations["listSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a submission and promote it to a real organization.
         * @description Atomically: creates an `organizations` row (status `approved`)
         *     from the submission payload, links it to the submitted region
         *     slugs via `organization_regions`, sets
         *     `submissions.promoted_org_id`, and marks the submission
         *     `approved`.
         */
        post: operations["approveSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a submission with a reason. */
        post: operations["rejectSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description ISO-style country code. v1 ships with `US` and `CA`; additional
         *     countries (`DE`, `FR`, `UK`, `AU`, …) are added without spec
         *     changes as data is loaded.
         * @example US
         */
        Country: string;
        /**
         * @description Drives result grouping in `/lookup`. `local` for city/county
         *     regions; `regional` for metro/state/province/multi-state.
         * @enum {string}
         */
        ScopeTier: "local" | "regional";
        /**
         * @description Free-form taxonomy for region granularity. The recommended
         *     vocabulary uses country-prefixed values: `us:city`, `us:borough`,
         *     `us:county`, `us:metro`, `us:state`, `us:multi-state`,
         *     `us:transit-federation`, `ca:province`, `ca:regional-district`,
         *     `ca:city`, `de:land`, `de:bezirk`, `de:kreisfreie-stadt`,
         *     `de:transit-federation`, `fr:commune`, `fr:departement`,
         *     `fr:region`, `fr:metropole`. Clients should treat unknown kinds
         *     gracefully (e.g. fall back to displaying `name`).
         * @example us:metro
         */
        RegionKind: string;
        /**
         * @description Lifecycle state of a public submission.
         * @enum {string}
         */
        SubmissionStatus: "pending" | "approved" | "rejected";
        /**
         * @description A geographic unit an organization can serve. Regions form a
         *     directed acyclic graph; `parent_slugs` lists the direct parents
         *     (not transitive). Empty for top-of-hierarchy regions (states,
         *     multi-state regions, transit federations).
         */
        Region: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["RegionKind"];
            /** @example Brooklyn */
            name: string;
            /**
             * @description Globally unique across countries.
             * @example brooklyn
             */
            slug: string;
            country: components["schemas"]["Country"];
            scope_tier: components["schemas"]["ScopeTier"];
            /**
             * @description Direct parents in the region graph. Clients can walk these
             *     to render breadcrumbs without a second request.
             */
            parent_slugs: string[];
        };
        /**
         * @description A single advocacy organization. `regions` is denormalized onto
         *     the organization for ergonomic JSON output — it lists every
         *     region the org serves, not just the regions that matched the
         *     current query.
         */
        Org: {
            /** Format: int64 */
            id: number;
            /** @example transalt */
            slug: string;
            /** @example Transportation Alternatives */
            name: string;
            /** @example NYC-wide advocacy for walking, biking, and public transit. */
            short_desc: string;
            /**
             * Format: uri
             * @example https://www.transalt.org
             */
            website_url: string;
            /**
             * Format: uri
             * @description Optional. URL of the org's contact page.
             */
            contact_url?: string;
            /**
             * @description Open-ended labels. The canonical set is documented in
             *     `CLAUDE.md` (transit, safe-streets, cycling, walking,
             *     vision-zero, policy, grassroots, political, neighborhood);
             *     new labels may be introduced via seed data.
             */
            tags: string[];
            regions: components["schemas"]["Region"][];
        };
        /**
         * @description An `Org` augmented with the per-lookup `matched_region_slugs`
         *     field. Returned only by `/api/v1/lookup`; other endpoints that
         *     return organizations use the base `Org` schema.
         */
        LookupOrg: components["schemas"]["Org"] & {
            /**
             * @description Slugs of the regions whose membership caused this org
             *     to surface for the current lookup. A non-empty subset
             *     of the org's `regions[*].slug`. Useful for
             *     explainability and debugging.
             */
            matched_region_slugs: string[];
        };
        LookupQuery: {
            /** @example 11217 */
            postal_code: string;
            country: components["schemas"]["Country"];
        };
        /**
         * @description Response shape of `GET /api/v1/lookup`. `local` and `regional`
         *     are always present (possibly empty arrays).
         *     `resolved_ancestry` is the postal code's leaf region followed
         *     by all ancestors, ordered most-specific first — clients can use
         *     it to render breadcrumbs without walking the graph themselves.
         */
        LookupResult: {
            query: components["schemas"]["LookupQuery"];
            /** @example Brooklyn, NYC — New York Metro */
            resolved_place_label: string;
            resolved_ancestry: components["schemas"]["Region"][];
            local: components["schemas"]["LookupOrg"][];
            regional: components["schemas"]["LookupOrg"][];
        };
        /** @description A metro region plus its approved-org count, for the browse-by-metro panel. */
        MetroSummary: {
            region: components["schemas"]["Region"];
            /** Format: int32 */
            org_count: number;
        };
        /** @description A metro region with the approved organizations that serve it. */
        MetroDetail: {
            region: components["schemas"]["Region"];
            orgs: components["schemas"]["Org"][];
        };
        /** @description The proposed organization, as submitted by a member of the public. */
        SubmissionPayload: {
            name: string;
            short_desc: string;
            /** Format: uri */
            website_url: string;
            /**
             * Format: uri
             * @description Optional.
             */
            contact_url?: string;
            tags: string[];
            /**
             * @description Slugs of the regions this organization serves (e.g.
             *     `["brooklyn-ny","nyc-metro"]`). The server resolves these
             *     against the `regions` table at approval time.
             */
            region_slugs: string[];
        };
        /** @description Request body for `POST /api/v1/submissions`. */
        NewSubmissionRequest: {
            payload: components["schemas"]["SubmissionPayload"];
            /** @description Optional. The submitter's name. */
            submitter_name?: string;
            /**
             * Format: email
             * @description Optional. The submitter's contact email.
             */
            submitter_email?: string;
            /** @description Optional. Free-form note to the moderators. */
            submitter_note?: string;
        };
        /** @description A queued or processed public submission. */
        Submission: {
            /** Format: int64 */
            id: number;
            payload: components["schemas"]["SubmissionPayload"];
            submitter_name?: string;
            /** Format: email */
            submitter_email?: string;
            submitter_note?: string;
            status: components["schemas"]["SubmissionStatus"];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Set when status moves from `pending` to a terminal state.
             */
            processed_at?: string;
            /**
             * Format: int64
             * @description Set on approval to the ID of the created organization.
             */
            promoted_org_id?: number;
            /** @description Set on rejection. */
            rejection_reason?: string;
        };
        /** @description Request body for `POST /api/v1/admin/submissions/{id}/reject`. */
        RejectSubmissionRequest: {
            /** @description Free-form note shown to the submitter if email notifications are enabled, and persisted for audit. */
            reason: string;
        };
        /**
         * @description Standard [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html)
         *     Problem Details object. Returned on every non-2xx response with
         *     content-type `application/problem+json`.
         *
         *     The `type` field is a stable URI identifying the problem class.
         *     The current v1 type values are:
         *
         *     - `https://urbanistatlas.com/problems/validation` — request was
         *       malformed or missing a required field (HTTP 400).
         *     - `https://urbanistatlas.com/problems/not-found` — the
         *       requested resource does not exist (HTTP 404).
         *     - `https://urbanistatlas.com/problems/unauthorized` — missing
         *       or invalid bearer token on a protected endpoint (HTTP 401).
         *     - `https://urbanistatlas.com/problems/conflict` — the requested
         *       state transition is not valid given current state (e.g.
         *       approving a non-pending submission) (HTTP 409).
         *     - `https://urbanistatlas.com/problems/rate-limited` — too many
         *       requests from this source (HTTP 429). A `Retry-After` header
         *       is also returned.
         *     - `https://urbanistatlas.com/problems/internal` — an
         *       unexpected server error (HTTP 500).
         *
         *     These URIs are stable identifiers; they do not necessarily
         *     dereference to a human-readable page yet.
         *
         *     Additional fields beyond the RFC's standard five are permitted
         *     and consumers should ignore unknown fields. The `request_id`
         *     extension is included on every error response and matches the
         *     `X-Request-ID` response header so clients can quote it when
         *     reporting bugs.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI reference that identifies the problem type. When
             *     absent or `about:blank`, the `title` alone identifies the
             *     problem.
             * @default about:blank
             * @example https://urbanistatlas.com/problems/validation
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem type. Should
             *     not change between occurrences of the same problem type,
             *     except for localization.
             * @example Bad Request
             */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code generated by the origin server. Mirrors
             *     the response's status line; included in the body so it
             *     survives proxies that mangle status codes.
             * @example 400
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             *     Safe to display to end users.
             * @example postal_code is required
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference that identifies the specific occurrence of
             *     the problem — typically the request path.
             * @example /api/v1/lookup
             */
            instance?: string;
            /**
             * @description Extension field. The server-side request ID; matches the
             *     `X-Request-ID` response header. Useful for users to quote
             *     when reporting bugs.
             * @example a1b2c3d4e5f6g7h8
             */
            request_id?: string;
        };
    };
    responses: {
        /**
         * @description Request was malformed or missing required parameters.
         *     Response body is an RFC 9457 problem document with
         *     `type` typically `https://urbanistatlas.com/problems/validation`.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Missing or invalid bearer token.
         *     Response body is an RFC 9457 problem document with
         *     `type` `https://urbanistatlas.com/problems/unauthorized`.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description The requested resource was not found.
         *     Response body is an RFC 9457 problem document with
         *     `type` `https://urbanistatlas.com/problems/not-found`.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Rate limit exceeded. Includes a `Retry-After` header.
         *     Response body is an RFC 9457 problem document with
         *     `type` `https://urbanistatlas.com/problems/rate-limited`.
         */
        TooManyRequests: {
            headers: {
                /** @description Seconds the client should wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description An unexpected server error occurred. The `request_id`
         *     extension field (and the `X-Request-ID` response header)
         *     identify the request in server logs.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /**
         * @description US ZIP code (e.g. `11217`) or Canadian postal code or FSA
         *     (e.g. `M5V` or `M5V 3A8`). Whitespace is trimmed; CA codes are
         *     truncated to their 3-character FSA server-side.
         */
        PostalCodeQuery: string;
        /** @description ISO-style country code. Case-insensitive. */
        CountryQuery: components["schemas"]["Country"];
        /** @description The metro region's slug (e.g. `nyc-metro`). */
        MetroSlug: string;
        /** @description The submission's numeric ID. */
        SubmissionID: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3 specification, in YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    lookup: {
        parameters: {
            query: {
                /**
                 * @description US ZIP code (e.g. `11217`) or Canadian postal code or FSA
                 *     (e.g. `M5V` or `M5V 3A8`). Whitespace is trimmed; CA codes are
                 *     truncated to their 3-character FSA server-side.
                 */
                postal_code: components["parameters"]["PostalCodeQuery"];
                /** @description ISO-style country code. Case-insensitive. */
                country: components["parameters"]["CountryQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lookup succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listMetros: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metros with counts, ordered by org count descending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetroSummary"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getMetro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The metro region's slug (e.g. `nyc-metro`). */
                slug: components["parameters"]["MetroSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The metro region and its organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetroDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRecent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recently approved organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission accepted into the queue. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listSubmissions: {
        parameters: {
            query?: {
                /** @description Filter by submission status. Defaults to `pending`. */
                status?: components["schemas"]["SubmissionStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submissions matching the filter, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    approveSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The submission's numeric ID. */
                id: components["parameters"]["SubmissionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission approved; returns the updated submission with `promoted_org_id` set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Submission is not in `pending` state.
             *     Response body is an RFC 9457 problem document with
             *     `type` `https://urbanistatlas.com/problems/conflict`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    rejectSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The submission's numeric ID. */
                id: components["parameters"]["SubmissionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission rejected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Submission is not in `pending` state.
             *     Response body is an RFC 9457 problem document with
             *     `type` `https://urbanistatlas.com/problems/conflict`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
