/**
 * Typed HTTP client for the Urbanist Atlas API.
 *
 * All wire shapes (request/response bodies, enums, error envelopes) come
 * from `./api.gen.ts`, which is generated by `openapi-typescript` from
 * `../api/openapi.yaml`. Do not hand-roll types in this file — if you
 * need something new, add it to the spec and run `npm run generate:api`.
 *
 * The base URL is read from `import.meta.env.VITE_API_BASE` at build
 * time and defaults to the dev server URL. Set it in `.env.production`
 * (or via the Cloudflare Pages dashboard) for prod builds.
 */
import type { components } from './api.gen.ts';

// Re-export the wire shapes that callers will commonly touch, so they
// can `import { LookupResult } from '@/lib/api'` without reaching into
// the generated file directly.
export type Country = components['schemas']['Country'];
export type Region = components['schemas']['Region'];
export type Org = components['schemas']['Org'];
export type LookupQuery = components['schemas']['LookupQuery'];
export type LookupResult = components['schemas']['LookupResult'];
export type MetroSummary = components['schemas']['MetroSummary'];
export type MetroDetail = components['schemas']['MetroDetail'];
export type Submission = components['schemas']['Submission'];
export type SubmissionPayload = components['schemas']['SubmissionPayload'];
export type NewSubmissionRequest = components['schemas']['NewSubmissionRequest'];
export type ProblemDetails = components['schemas']['ProblemDetails'];

const DEFAULT_API_BASE = 'http://localhost:8080';

/** Where the API lives. Set `VITE_API_BASE` to override at build time. */
export const apiBase: string = import.meta.env.VITE_API_BASE ?? DEFAULT_API_BASE;

/**
 * Error thrown for any non-2xx response from the API. Carries the HTTP
 * status, the parsed RFC 9457 problem document (when the server sent
 * one), and the request ID for log correlation.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly problem: ProblemDetails | undefined;
  readonly requestId: string | undefined;

  constructor(
    status: number,
    message: string,
    problem: ProblemDetails | undefined,
    requestId: string | undefined,
  ) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.problem = problem;
    this.requestId = requestId;
  }
}

/**
 * Low-level fetch wrapper. Prepends {@link apiBase} to `path`, sets
 * `Accept: application/json`, throws {@link ApiError} on non-2xx
 * responses (parsing `application/problem+json` bodies when present),
 * and returns the parsed JSON body as `T`.
 *
 * Callers should usually reach for a higher-level wrapper (e.g.
 * {@link lookup}) rather than calling this directly.
 */
export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const url = path.startsWith('http') ? path : `${apiBase}${path}`;
  const headers = new Headers(init?.headers);
  if (!headers.has('Accept')) {
    headers.set('Accept', 'application/json');
  }

  const response = await fetch(url, { ...init, headers });
  const requestId = response.headers.get('X-Request-ID') ?? undefined;

  if (!response.ok) {
    let problem: ProblemDetails | undefined;
    const contentType = response.headers.get('Content-Type') ?? '';
    if (contentType.includes('application/problem+json')) {
      try {
        problem = (await response.json()) as ProblemDetails;
      } catch {
        // Body wasn't valid JSON after all; ignore and fall through to a
        // bare-status error.
      }
    }
    const message = problem?.title ?? problem?.detail ?? `HTTP ${response.status}`;
    throw new ApiError(response.status, message, problem, requestId);
  }

  return (await response.json()) as T;
}

/**
 * `GET /api/v1/lookup?postal_code=…&country=…` — the main search.
 * Resolves to a {@link LookupResult} with `local` and `regional` orgs
 * for the postal code; throws {@link ApiError} on a non-2xx response
 * (including the 404 returned for unresolvable codes).
 */
export function lookup(
  postal_code: string,
  country: Country,
  init?: RequestInit,
): Promise<LookupResult> {
  const params = new URLSearchParams({ postal_code, country });
  return apiFetch<LookupResult>(`/api/v1/lookup?${params.toString()}`, init);
}
