package httpapi

import (
	"encoding/json"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/mjrossi/urbanist-atlas/api/internal/httpapi/oapi"
	"github.com/mjrossi/urbanist-atlas/api/pkg/atlas"
)

// newTestServer builds an httptest.Server backed by the full router,
// memory-store, and the dev fixtures, so handler tests run end-to-end
// through the same middleware stack the production server uses.
func newTestServer(t *testing.T) *httptest.Server {
	t.Helper()
	store := atlas.NewMemStore()
	atlas.LoadDevFixtures(store)
	handler := New(Config{
		Store:      store,
		Logger:     slog.New(slog.DiscardHandler),
		APIVersion: "v1",
	})
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	return srv
}

func TestLookup_HappyPath_ReturnsOAPIShape(t *testing.T) {
	srv := newTestServer(t)

	resp, err := http.Get(srv.URL + "/api/v1/lookup?postal_code=11217&country=US")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status: want 200, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		t.Errorf("Content-Type: want application/json prefix, got %q", ct)
	}

	var got oapi.LookupResult
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if got.Query.PostalCode != "11217" || got.Query.Country != "US" {
		t.Errorf("query: %+v", got.Query)
	}
	if len(got.Local) == 0 {
		t.Errorf("want at least one local org, got 0")
	}
	if len(got.Regional) == 0 {
		t.Errorf("want at least one regional org, got 0")
	}
	// At least one regional org from the fixtures has multiple regions.
	for _, o := range got.Regional {
		if o.Slug == "tri-state-transportation-campaign" && len(o.Regions) == 0 {
			t.Error("regional org has no regions populated; full set is required by the wire contract")
		}
	}
}

func TestLookup_MissingPostalCode_ReturnsProblemJSON(t *testing.T) {
	srv := newTestServer(t)

	resp, err := http.Get(srv.URL + "/api/v1/lookup?country=US")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("status: want 400, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "application/problem+json" {
		t.Errorf("Content-Type: want application/problem+json, got %q", ct)
	}

	body, _ := io.ReadAll(resp.Body)
	var prob oapi.ProblemDetails
	if err := json.Unmarshal(body, &prob); err != nil {
		t.Fatalf("decode problem: %v", err)
	}
	want := oapi.ProblemDetails{
		Type:   problemValidation,
		Title:  "Bad Request",
		Status: int32(http.StatusBadRequest),
	}
	want.Detail = stringPtr("postal_code is required")
	want.Instance = stringPtr("/api/v1/lookup")
	// request_id is randomly-generated by middleware; copy from got.
	if prob.RequestId == nil || *prob.RequestId == "" {
		t.Errorf("request_id: want non-empty, got %v", prob.RequestId)
	}
	want.RequestId = prob.RequestId
	if diff := cmp.Diff(want, prob); diff != "" {
		t.Errorf("problem details (-want +got):\n%s", diff)
	}
}

func TestLookup_PostalCodeNotFound_ReturnsProblemJSON(t *testing.T) {
	srv := newTestServer(t)

	resp, err := http.Get(srv.URL + "/api/v1/lookup?postal_code=00000&country=US")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("status: want 404, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "application/problem+json" {
		t.Errorf("Content-Type: want application/problem+json, got %q", ct)
	}

	var prob oapi.ProblemDetails
	if err := json.NewDecoder(resp.Body).Decode(&prob); err != nil {
		t.Fatalf("decode problem: %v", err)
	}
	if prob.Type != problemNotFound {
		t.Errorf("type: want %q, got %q", problemNotFound, prob.Type)
	}
	if prob.Status != int32(http.StatusNotFound) {
		t.Errorf("status: want 404, got %d", prob.Status)
	}
	if prob.Title != "Not Found" {
		t.Errorf("title: want %q, got %q", "Not Found", prob.Title)
	}
}

func TestLookup_UnknownCountry_ReturnsNotFound(t *testing.T) {
	// Per the slice #4.6 loader-engineering work, the handler no longer
	// gates on a known-country whitelist (Country is opaque per
	// pkg/atlas/atlas.go). An unknown country with an unknown postal
	// code falls through to atlas.Lookup → ErrPostalCodeNotFound → 404.
	srv := newTestServer(t)

	resp, err := http.Get(srv.URL + "/api/v1/lookup?postal_code=11217&country=ZZ")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("status: want 404, got %d", resp.StatusCode)
	}

	var prob oapi.ProblemDetails
	if err := json.NewDecoder(resp.Body).Decode(&prob); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if prob.Type != problemNotFound {
		t.Errorf("type: want %q, got %q", problemNotFound, prob.Type)
	}
}

func TestLookup_MissingCountry_ReturnsProblemJSON(t *testing.T) {
	srv := newTestServer(t)

	resp, err := http.Get(srv.URL + "/api/v1/lookup?postal_code=11217")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("status: want 400, got %d", resp.StatusCode)
	}

	var prob oapi.ProblemDetails
	if err := json.NewDecoder(resp.Body).Decode(&prob); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if prob.Detail == nil || *prob.Detail != "country is required" {
		t.Errorf("detail: %v", prob.Detail)
	}
}

func stringPtr(s string) *string { return &s }
