package httpapi

import (
	"encoding/json"
	"net/http"

	"github.com/mjrossi/urbanist-atlas/api/internal/httpapi/oapi"
)

// Stable problem-type URIs. The catalog and its meanings are
// documented in api/openapi.yaml's ProblemDetails schema; mirror
// changes here when the spec changes.
//
// Only the URIs that the handlers in this slice emit are listed.
// `conflict` and `rate-limited` will be added by the slices that need
// them (submissions / admin endpoints, slice #5; rate limiting, slice
// #27) to keep this file lint-clean in the interim.
const (
	problemValidation   = "https://urbanistatlas.com/problems/validation"
	problemNotFound     = "https://urbanistatlas.com/problems/not-found"
	problemInternal     = "https://urbanistatlas.com/problems/internal"
	problemUnauthorized = "https://urbanistatlas.com/problems/unauthorized"
)

// writeJSON emits an arbitrary value as application/json. Used for
// successful responses; error responses go through writeProblem so
// they get RFC 9457's `application/problem+json` content type.
func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

// writeProblem emits an RFC 9457 Problem Details object with
// content-type application/problem+json. The shape mirrors the
// `ProblemDetails` schema generated by oapi-codegen from openapi.yaml.
//
// `detail` and `instance` may be empty; they're omitted from the JSON
// when zero. `requestID` is included as the spec's `request_id`
// extension so users can quote it when reporting bugs.
func writeProblem(w http.ResponseWriter, r *http.Request, status int, typeURI, title, detail, requestID string) {
	body := oapi.ProblemDetails{
		Type:   typeURI,
		Title:  title,
		Status: int32(status),
	}
	if detail != "" {
		body.Detail = &detail
	}
	if r != nil {
		instance := r.URL.Path
		body.Instance = &instance
	}
	if requestID != "" {
		body.RequestId = &requestID
	}

	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}
