package httpapi

import (
	"encoding/json"
	"net/http"
)

// Stable problem-type URIs. The catalog and its meanings are
// documented in api/openapi.yaml's ProblemDetails schema; mirror
// changes here when the spec changes.
const (
	problemValidation   = "https://urbanistatlas.com/problems/validation"
	problemNotFound     = "https://urbanistatlas.com/problems/not-found"
	problemInternal     = "https://urbanistatlas.com/problems/internal"
	problemUnauthorized = "https://urbanistatlas.com/problems/unauthorized"
	problemConflict     = "https://urbanistatlas.com/problems/conflict"
	problemRateLimited  = "https://urbanistatlas.com/problems/rate-limited"
)

// writeJSON emits an arbitrary value as application/json. Used for
// successful responses; error responses go through writeProblem so
// they get RFC 9457's `application/problem+json` content type.
func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

// problemBody is the on-the-wire shape for an RFC 9457 Problem
// Details object. We marshal this directly (rather than the
// oapi-generated ProblemDetails) so we can attach the optional
// `errors` extension keyed by field name — per RFC 9457 §3.2,
// additional members beyond the standard five are permitted.
type problemBody struct {
	Type      string            `json:"type"`
	Title     string            `json:"title"`
	Status    int               `json:"status"`
	Detail    string            `json:"detail,omitempty"`
	Instance  string            `json:"instance,omitempty"`
	RequestID string            `json:"request_id,omitempty"`
	Errors    map[string]string `json:"errors,omitempty"`
}

// writeProblem emits an RFC 9457 Problem Details object with
// content-type application/problem+json. The shape mirrors the
// `ProblemDetails` schema generated by oapi-codegen from openapi.yaml.
//
// `detail` and `instance` may be empty; they're omitted from the JSON
// when zero. `requestID` is included as the spec's `request_id`
// extension so users can quote it when reporting bugs.
func writeProblem(w http.ResponseWriter, r *http.Request, status int, typeURI, title, detail, requestID string) {
	writeProblemWithErrors(w, r, status, typeURI, title, detail, requestID, nil)
}

// writeProblemWithErrors is writeProblem plus the optional `errors`
// extension — a `{field: message}` map clients can dispatch to
// per-field form validators (e.g. react-hook-form's setError). Empty
// or nil maps fall back to writeProblem's plain shape.
func writeProblemWithErrors(w http.ResponseWriter, r *http.Request, status int, typeURI, title, detail, requestID string, fieldErrors map[string]string) {
	body := problemBody{
		Type:      typeURI,
		Title:     title,
		Status:    status,
		Detail:    detail,
		RequestID: requestID,
		Errors:    fieldErrors,
	}
	if r != nil {
		body.Instance = r.URL.Path
	}

	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}
